export const data = [
    {
        nota: 10,
        nome: "20th Century Boys",
        lancamento: "1999",
        genero: ["Seinen"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/5/260006.jpg",
    },
    {
        nota: 10,
        nome: "21st Century Boys",
        lancamento: "2006",
        genero: ["Seinen"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/2/263856.jpg",
    },
    {
        nota: 10,
        nome: "Memories of Murder",
        lancamento: "2003",
        genero: ["Suspense", "Mistério"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://m.media-amazon.com/images/M/MV5BYmRjOWE5NmMtYTdkYS00ODFlLWJiMTMtYzE2NDZlZjlkZDQ0XkEyXkFqcGc@._V1_QL75_UX285_CR0,0,285,422_.jpg",
    },
    {
        nota: 10,
        nome: "House M.D.",
        lancamento: "2004",
        genero: ["Drama"],
        tempo: "Completo",
        tipo: "Série",
        cover: "https://images.justwatch.com/poster/305563849/s718/house.jpg",
    },
    {
        nota: 10,
        nome: "Kaiji",
        lancamento: "2007",
        genero: ["Seinen", "Aposta"],
        tempo: "Completo",
        tipo: "Anime",
        cover: "https://cdn.myanimelist.net/images/anime/12/80032.jpg",
    },
    {
        nota: 10,
        nome: "Viral Hit",
        lancamento: "2019",
        genero: ["Drama", "Arte Marcial"],
        tempo: "Completo",
        tipo: "Manwha",
        cover: "https://cdn.myanimelist.net/images/manga/1/248716.jpg",
    },
    {
        nota: 10,
        nome: "Lookism",
        lancamento: "2014",
        genero: ["Drama", "Arte Marcial"],
        tempo: "Incompleto",
        tipo: "Manwha",
        cover: "https://upload.wikimedia.org/wikipedia/en/1/17/Lookism_Volume_1_Cover.jpg",
    },
    {
        nota: 10,
        nome: "Holyland",
        lancamento: "2000",
        genero: ["Seinen"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/3/258962.jpg",
    },
    {
        nota: 10,
        nome: "Kokou no Hito",
        lancamento: "2007",
        genero: ["Seinen"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/1/324690.jpg",
    },
    {
        nota: 10,
        nome: "Chainsaw Man",
        lancamento: "2018",
        genero: ["Seinen"],
        tempo: "Incompleto",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/3/216464.jpg",
    },
    {
        nota: 10,
        nome: "Freesia",
        lancamento: "2001",
        genero: ["Seinen"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/1/321361.jpg",
    },
    {
        nota: 10,
        nome: "Tengen Toppa Gurren Lagann",
        lancamento: "2007",
        genero: ["Mecha"],
        tempo: "Completo",
        tipo: "Anime",
        cover: "https://cdn.myanimelist.net/images/anime/4/5123.jpg",
    },
    {
        nota: 10,
        nome: "Berserk",
        lancamento: "1989",
        genero: ["Seinen", "Fantasia"],
        tempo: "Incompleto",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/1/157897.jpg",
    },
    {
        nota: 10,
        nome: "Homunculus",
        lancamento: "2003",
        genero: ["Seinen", "Terror"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/1/318.jpg",
    },
    {
        nota: 10,
        nome: "Koroshiya 1",
        lancamento: "1998",
        genero: ["Seinen", "Terror"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/3/174206.webp",
    },
    {
        nota: 10,
        nome: "Death Note",
        lancamento: "2006",
        genero: ["Psicológico"],
        tempo: "Completo",
        tipo: "Anime",
        cover: "https://cdn.myanimelist.net/images/anime/1079/138100.jpg",
    },
    {
        nota: 10,
        nome: "Chi no Wadachi",
        lancamento: "2017",
        genero: ["Seinen", "Terror", "Psicológico"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/1/200350.jpg",
    },
    {
        nota: 10,
        nome: "Parasite",
        lancamento: "2019",
        genero: ["Drama"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    },
    {
        nota: 10,
        nome: "Hunter x Hunter",
        lancamento: "2011",
        genero: ["Shounen"],
        tempo: "Completo",
        tipo: "Anime",
        cover: "https://m.media-amazon.com/images/M/MV5BYzYxOTlkYzctNGY2MC00MjNjLWIxOWMtY2QwYjcxZWIwMmEwXkEyXkFqcGc@._V1_QL75_UY562_CR7,0,380,562_.jpg",
    },
    {
        nota: 9,
        nome: "Cyberpunk: Edgerunners",
        lancamento: "2022",
        genero: ["Ação", "Drama", "Cyberpunk"],
        tempo: "Completo",
        tipo: "Anime",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/lqcDVZ8pyk08AVftMBildDR3QUK.jpg",
    },
    {
        nota: 9,
        nome: "Ajin",
        lancamento: "2012",
        genero: ["Seinen", "Terror"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/3/307700.jpg",
    },
    {
        nota: 9,
        nome: "Battle Royale",
        lancamento: "2000",
        genero: ["Seinen"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/1/262978.jpg",
    },
    {
        nota: 9,
        nome: "Inuyashiki",
        lancamento: "2014",
        genero: ["Seinen"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/2/156353.webp",
    },
    {
        nota: 9,
        nome: "The Fable",
        lancamento: "2014",
        genero: ["Seinen"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/2/152911.jpg",
    },
    {
        nota: 9,
        nome: "Steins;Gate",
        lancamento: "2011",
        genero: ["Ficção Científica"],
        tempo: "Completo",
        tipo: "Anime",
        cover: "https://m.media-amazon.com/images/M/MV5BZjI1YjZiMDUtZTI3MC00YTA5LWIzMmMtZmQ0NTZiYWM4NTYwXkEyXkFqcGc@._V1_QL75_UX380_CR0,4,380,562_.jpg",
    },
    {
        nota: 9,
        nome: "Bastard",
        lancamento: "2014",
        genero: ["Terror", "Drama"],
        tempo: "Completo",
        tipo: "Manwha",
        cover: "https://cdn.myanimelist.net/images/manga/1/205549.jpg",
    },
    {
        nota: 9,
        nome: "I am a Hero",
        lancamento: "2009",
        genero: ["Seinen", "Terror"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/1/121183.jpg",
    },
    {
        nota: 9,
        nome: "Gantz",
        lancamento: "2000",
        genero: ["Seinen", "Terror"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/1/278020.jpg",
    },
    {
        nota: 9,
        nome: "The Silent Sea",
        lancamento: "2021",
        genero: ["Drama", "Ficção Científica"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/fFT0IgqtCOks4munDTxQwkvNJkd.jpg",
    },
    {
        nota: 9,
        nome: "Mob Psycho 100",
        lancamento: "2016",
        genero: ["Drama"],
        tempo: "Incompleto",
        tipo: "Anime",
        cover: "https://cdn.myanimelist.net/images/anime/5/79183l.jpg",
    },
    {
        nota: 9,
        nome: "Attack on Titan",
        lancamento: "2013",
        genero: ["Shounen"],
        tempo: "Completo",
        tipo: "Anime",
        cover: "https://cdn.myanimelist.net/images/anime/10/47347.jpg",
    },
    {
        nota: 9,
        nome: "Naruto",
        lancamento: "2002",
        genero: ["Shounen"],
        tempo: "Completo",
        tipo: "Anime",
        cover: "https://cdn.myanimelist.net/images/anime/1141/142503.jpg",
    },
    {
        nota: 9,
        nome: "Naruto: Shippuden",
        lancamento: "2007",
        genero: ["Shounen"],
        tempo: "Completo",
        tipo: "Anime",
        cover: "https://cdn.myanimelist.net/images/anime/1565/111305.jpg",
    },
    {
        nota: 9,
        nome: "Hideout",
        lancamento: "2010",
        genero: ["Seinen", "Terror"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/2/65719.webp",
    },
    {
        nota: 9,
        nome: "Perfect Blue",
        lancamento: "1997",
        genero: ["Psicológico"],
        tempo: "Completo",
        tipo: "Anime",
        cover: "https://cdn.myanimelist.net/images/anime/1982/114564l.jpg",
    },
    {
        nota: 9,
        nome: "Ghost in the Shell",
        lancamento: "1995",
        genero: ["Ficção Científica", "Cyberpunk"],
        tempo: "Completo",
        tipo: "Anime",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/9gC88zYUBARRSThcG93MvW14sqx.jpg",
    },
    {
        nota: 9,
        nome: "Charlotte",
        lancamento: "2015",
        genero: ["Drama", "Ficção Científica", "Romance"],
        tempo: "Completo",
        tipo: "Anime",
        cover: "https://cdn.myanimelist.net/images/anime/1826/147276.jpg",
    },
    {
        nota: 9,
        nome: "Jojo Bizarre Adventure",
        lancamento: "2012",
        genero: ["Drama", "Ação"],
        tempo: "Completo",
        tipo: "Anime",
        cover: "https://m.media-amazon.com/images/M/MV5BMzIyNzY4NTMtNmVhYS00OWFhLTkwMWMtOGFkNTdmNWU2ZDdiXkEyXkFqcGc@._V1_QL75_UY562_CR7,0,380,562_.jpg",
    },
    {
        nota: 9,
        nome: "JoJo no Kimyou na Bouken Part 7: Steel Ball Run",
        lancamento: "2004",
        genero: ["Seinen"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/3/179882.jpg",
    },
    {
        nota: 9,
        nome: "JoJo no Kimyou na Bouken Part 6: Stone Ocean",
        lancamento: "1999",
        genero: ["Seinen"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/2/238164.jpg",
    },
    {
        nota: 9,
        nome: "Kuruko no Basket",
        lancamento: "2012",
        genero: ["Esporte"],
        tempo: "Completo",
        tipo: "Anime",
        cover: "https://cdn.myanimelist.net/images/anime/11/50453.jpg",
    },
    {
        nota: 9,
        nome: "Donnie Darko",
        lancamento: "2001",
        genero: ["Drama", "Terror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/fhQoQfejY1hUcwyuLgpBrYs6uFt.jpg",
    },
    {
        nota: 9,
        nome: "Midsommar",
        lancamento: "2019",
        genero: ["Drama", "Terror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/7LEI8ulZzO5gy9Ww2NVCrKmHeDZ.jpg",
    },
    {
        nota: 9,
        nome: "Incantation",
        lancamento: "2022",
        genero: ["Drama", "Terror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/cWz28oGV3cSajWdziVQbqrYCmnX.jpg",
    },
    {
        nota: 9,
        nome: "Breaking Bad",
        lancamento: "2008",
        genero: ["Drama"],
        tempo: "Completo",
        tipo: "Série",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/ztkUQFLlC19CCMYHW9o1zWhJRNq.jpg",
    },
    {
        nota: 9,
        nome: "Usogui",
        lancamento: "2006",
        genero: ["Drama", "Ação", "Aposta"],
        tempo: "Incompleto",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/2/283743.jpg",
    },
    {
        nota: 9,
        nome: "One Piece",
        lancamento: "1999",
        genero: ["Drama", "Ação"],
        tempo: "Incompleto",
        tipo: "Anime",
        cover: "https://cdn.myanimelist.net/images/anime/1451/114315l.jpg",
    },
    {
        nota: 9,
        nome: "The Killer Inside",
        lancamento: "2018",
        genero: ["Seinen", "Terror"],
        tempo: "Incompleto",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/1/211898.webp",
    },
    {
        nota: 9,
        nome: "The Boxer",
        lancamento: "2019",
        genero: ["Seinen"],
        tempo: "Completo",
        tipo: "Manwha",
        cover: "https://cdn.myanimelist.net/images/manga/3/251281.jpg",
    },
    {
        nota: 9,
        nome: "The Horizon",
        lancamento: "2016",
        genero: ["Seinen"],
        tempo: "Completo",
        tipo: "Manwha",
        cover: "https://cdn.myanimelist.net/images/manga/1/229331l.jpg",
    },
    {
        nota: 9,
        nome: "Vagabond",
        lancamento: "1998",
        genero: ["Seinen"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/1/259070.jpg",
    },
    {
        nota: 9,
        nome: "Study Group",
        lancamento: "2019",
        genero: ["Drama", "Arte Marcial"],
        tempo: "Incompleto",
        tipo: "Manwha",
        cover: "https://cdn.myanimelist.net/images/manga/1/260634.jpg",
    },
    {
        nota: 9,
        nome: "Blue Lock",
        lancamento: "2018",
        genero: ["Shounen", "Esporte"],
        tempo: "Incompleto",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/5/213340.jpg",
    },
    {
        nota: 9,
        nome: "Blue Lock",
        lancamento: "2022",
        genero: ["Shounen", "Esporte"],
        tempo: "Completo",
        tipo: "Anime",
        cover: "https://cdn.myanimelist.net/images/anime/1258/126929.jpg",
    },
    {
        nota: 9,
        nome: "O Poço",
        lancamento: "2019",
        genero: ["Drama", "Terror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/iXvQnzy6JCAx1PiQEKXuTY04ZHl.jpg",
    },
    {
        nota: 9,
        nome: "O Poço 2",
        lancamento: "2024",
        genero: ["Drama", "Terror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/tvIpBg12IIA5Dr9Sjn38ygS1vQp.jpg",
    },
    {
        nota: 9,
        nome: "Shuumatsu no Valkyrie",
        lancamento: "2017",
        genero: ["Drama", "Ação", "Luta"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/3/209957.jpg",
    },
    {
        nota: 9,
        nome: "Oppenheimer",
        lancamento: "2023",
        genero: ["Drama"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    },
    {
        nota: 9,
        nome: "Adolescence",
        lancamento: "2025",
        genero: ["Drama"],
        tempo: "Completo",
        tipo: "Série",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/tDHWWReefmOOjBCJZUck8cNwssk.jpg",
    },
    {
        nota: 9,
        nome: "Nightcrawler",
        lancamento: "2014",
        genero: ["Drama"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/j9HrX8f7GbZQm1BrBiR40uFQZSb.jpg",
    },
    {
        nota: 9,
        nome: "Druk",
        lancamento: "2020",
        genero: ["Drama"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/aDcIt4NHURLKnAEu7gow51Yd00Q.jpg",
    },
    {
        nota: 9,
        nome: "Weak Hero",
        lancamento: "2018",
        genero: ["Drama", "Arte Marcial"],
        tempo: "Completo",
        tipo: "Manwha",
        cover: "https://cdn.myanimelist.net/images/manga/3/232795.jpg",
    },
    {
        nota: 8,
        nome: "Teenage Mercenary",
        lancamento: "2018",
        genero: ["Drama", "Arte Marcial"],
        tempo: "Incompleto",
        tipo: "Manwha",
        cover: "https://cdn.myanimelist.net/images/manga/3/260540.jpg",
    },
    {
        nota: 8,
        nome: "God of Blackfield",
        lancamento: "2020",
        genero: ["Drama", "Arte Marcial"],
        tempo: "Incompleto",
        tipo: "Manwha",
        cover: "https://cdn.myanimelist.net/images/manga/2/261694.jpg",
    },
    {
        nota: 8,
        nome: "All You Need Is Kill",
        lancamento: "2014",
        genero: ["Seinen", "Ficção Científica"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/1/128447.jpg",
    },
    {
        nota: 8,
        nome: "Shigahime",
        lancamento: "2011 ",
        genero: ["Terror", "Seinen"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/2/203507.jpg",
    },
    {
        nota: 8,
        nome: "Apocalypse no Toride",
        lancamento: "2011 ",
        genero: ["Terror", "Zumbi", "Seinen"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/2/162053.jpg",
    },
    {
        nota: 8,
        nome: "Manager Kim",
        lancamento: "2021",
        genero: ["Drama", "Arte Marcial"],
        tempo: "Incompleto",
        tipo: "Manwha",
        cover: "https://cdn.myanimelist.net/images/manga/3/260734.jpg",
    },
    {
        nota: 8,
        nome: "Boku Girl",
        lancamento: "2013",
        genero: ["Romance", "Ecchi"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/2/158930l.jpg",
    },
    {
        nota: 8,
        nome: "Happiness",
        lancamento: "2015",
        genero: ["Terror", "Seinen"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/2/161562.jpg",
    },
    {
        nota: 8,
        nome: "Wind Breaker",
        lancamento: "2021",
        genero: ["Drama", "Arte Marcial"],
        tempo: "Incompleto",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/1/244074.jpg",
    },
    {
        nota: 8,
        nome: "A Quiet Place",
        lancamento: "2023",
        genero: ["Terror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/nAU74GmpUk7t5iklEp3bufwDq4n.jpg",
    },
    {
        nota: 8,
        nome: "I am a Hero",
        lancamento: "2009",
        genero: ["Zombie", "Terror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/4RnmHtCLtbBHD9jagVlcSzJTWX6.jpg",
    },
    {
        nota: 8,
        nome: "Annihilation",
        lancamento: "2018 ",
        genero: ["Drama", "Terror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/4YRplSk6BhH6PRuE9gfyw9byUJ6.jpg",
    },
    {
        nota: 8,
        nome: "REC",
        lancamento: "2007",
        genero: ["Zumbi", "Terror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://m.media-amazon.com/images/M/MV5BMDEzNDc5ODMtZTAyNi00MTNkLThkNGUtZGE2MDY0MjBiYjMzXkEyXkFqcGc@._V1_QL75_UX380_CR0,4,380,562_.jpg",
    },
    {
        nota: 8,
        nome: "REC 2",
        lancamento: "2009",
        genero: ["Zumbi", "Terror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://m.media-amazon.com/images/M/MV5BMTI4MjQ1MDE1MV5BMl5BanBnXkFtZTcwNzIxMDk0Mw@@._V1_QL75_UY562_CR2,0,380,562_.jpg",
    },
    {
        nota: 8,
        nome: "The Walking Dead",
        lancamento: "2010",
        genero: ["Zumbi", "Terror"],
        tempo: "Incompleto",
        tipo: "Série",
        cover: "https://m.media-amazon.com/images/M/MV5BYWQwMGRhNGEtZTNhMy00MzVjLWJhMjItYjcwMDljMTkyNTg2XkEyXkFqcGc@._V1_QL75_UX380_CR0,4,380,562_.jpg",
    },
    {
        nota: 8,
        nome: "All of Us Are Dead",
        lancamento: "2022",
        genero: ["Zumbi", "Terror"],
        tempo: "Completo",
        tipo: "Série",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/pTEFqAjLd5YTsMD6NSUxV6Dq7A6.jpg",
    },
    {
        nota: 8,
        nome: "The Truamn Show",
        lancamento: "1998",
        genero: ["Drama"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/vuza0WqY239yBXOadKlGwJsZJFE.jpg",
    },
    {
        nota: 8,
        nome: "Bird Box",
        lancamento: "2018",
        genero: ["Terror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/rGfGfgL2pEPCfhIvqHXieXFn7gp.jpg",
    },
    {
        nota: 8,
        nome: "Bebê Rena",
        lancamento: "2023",
        genero: ["Drama", "Terror"],
        tempo: "Completo",
        tipo: "Série",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/tN9OcbkAOPwHSr1sgMornZtQZBx.jpg",
    },
    {
        nota: 8,
        nome: "Alien",
        lancamento: "1979",
        genero: ["Drama", "Terror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/vfrQk5IPloGg1v9Rzbh2Eg3VGyM.jpg",
    },
    {
        nota: 8,
        nome: "#Alive",
        lancamento: "2020",
        genero: ["Zumbi", "Terror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/lZPvLUMYEPLTE2df1VW5FHTYC8N.jpg",
    },
    {
        nota: 8,
        nome: "Outside",
        lancamento: "2024",
        genero: ["Zumbi", "Terror"],
        tempo: "Completo",
        tipo: "Série",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/e2YYJYZrQkodvMGfgdSUH5LBPpr.jpg",
    },
    {
        nota: 8,
        nome: "Manhole",
        lancamento: "2004",
        genero: ["Terror", "Drama"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/2/67629.jpg",
    },
    {
        nota: 8,
        nome: "Whiplash",
        lancamento: "2014",
        genero: ["Drama"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
    },
    {
        nota: 8,
        nome: "Meus 84m²",
        lancamento: "2025",
        genero: ["Drama", "Suspense"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/5hlNv3Kd9xovvSgrslWhMriGpZ8.jpg",
    },
    {
        nota: 8,
        nome: "Classroom of the Elite",
        lancamento: "2017",
        genero: ["Drama", "Arte Marcial"],
        tempo: "Incompleto",
        tipo: "Anime",
        cover: "https://cdn.myanimelist.net/images/anime/7/86829l.jpg",
    },
    {
        nota: 8,
        nome: "X",
        lancamento: "2022",
        genero: ["Thriller", "Terror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/lopZSVtXzhFY603E9OqF7O1YKsh.jpg",
    },
    {
        nota: 8,
        nome: "Pearl",
        lancamento: "2022",
        genero: ["Thriller", "Terror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/z5uIG81pXyHKg7cUFIu84Wjn4NS.jpg",
    },
    {
        nota: 8,
        nome: "Late Night with the Devil",
        lancamento: "2023",
        genero: ["Terror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/mu8LRWT9GHkfiyHm7kgxT6YNvMW.jpg",
    },
    {
        nota: 8,
        nome: "Tokyo Gore Police",
        lancamento: "2008",
        genero: ["Thriller", "Terror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/smQV5DgyUVho8d1R67XnU1BkJAV.jpg",
    },
    {
        nota: 8,
        nome: "The Professional",
        lancamento: "1994",
        genero: ["Drama"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/bxB2q91nKYp8JNzqE7t7TWBVupB.jpg",
    },
    {
        nota: 8,
        nome: "The Devil All the Time",
        lancamento: "2020",
        genero: ["Drama", "Terror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/sdMZmKVvrnyYbl9Az4L6ehuIrFp.jpg",
    },
    {
        nota: 8,
        nome: "Saotome Senshu, Hitakakusu",
        lancamento: "2016",
        genero: ["Esporte", "Romance"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/1/189746.jpg",
    },
    {
        nota: 8,
        nome: "Shotgun Boy",
        lancamento: "2021",
        genero: ["Terror", "Sobrenatural"],
        tempo: "Completo",
        tipo: "Manwha",
        cover: "https://cdn.myanimelist.net/images/manga/2/260422.jpg",
    },
    {
        nota: 8,
        nome: "O Assassino",
        lancamento: "2023",
        genero: ["Drama"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://m.media-amazon.com/images/M/MV5BYzU2MTlkMTctNWI3MC00ODUzLTlmYzQtMzZjYjVmMmYwZGU0XkEyXkFqcGc@._V1_QL75_UX190_CR0,0,190,281_.jpg",
    },
    {
        nota: 8,
        nome: "Alice in Borderland",
        lancamento: "2020",
        genero: ["Drama"],
        tempo: "Completo",
        tipo: "Série",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/Ac8ruycRXzgcsndTZFK6ouGA0FA.jpg",
    },
    {
        nota: 8,
        nome: "Cure",
        lancamento: "1999",
        genero: ["Drama", "Terror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://m.media-amazon.com/images/M/MV5BMTI5MmFlZjgtNjNhNC00NTFlLWEzZTctYjNjZDdjYjVmNjExXkEyXkFqcGc@._V1_QL75_UY281_CR7,0,190,281_.jpg",
    },
    {
        nota: 8,
        nome: "20th Century Boys 1: Beginning of the End",
        lancamento: "2008",
        genero: ["Drama", "Terror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://m.media-amazon.com/images/M/MV5BMTMxMzY4NDM2NV5BMl5BanBnXkFtZTcwMjA3MDYyMg@@._V1_QL75_UY422_CR8,0,285,422_.jpg",
    },
    {
        nota: 8,
        nome: "The 8 Show",
        lancamento: "2024",
        genero: ["Drama", "Terror"],
        tempo: "Completo",
        tipo: "Série",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/umBNBnKThMmF1QQZixZ7rsYOowq.jpg",
    },
    {
        nota: 8,
        nome: "The Frog",
        lancamento: "2024",
        genero: ["Drama", "Terror"],
        tempo: "Completo",
        tipo: "Série",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/uMl2TzRs1LzTR9jyRNHnf5keqMV.jpg",
    },
    {
        nota: 8,
        nome: "Squid Game",
        lancamento: "2021",
        genero: ["Drama", "Terror"],
        tempo: "Completo",
        tipo: "Série",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/1QdXdRYfktUSONkl1oD5gc6Be0s.jpg",
    },
    {
        nota: 8,
        nome: "Battle Royale",
        lancamento: "2000",
        genero: ["Seinen"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://m.media-amazon.com/images/M/MV5BNjdlYzJlYzMtMWU3Yi00Y2FjLWJhYmUtNjM3YzdjYzZkOWMwXkEyXkFqcGc@._V1_QL75_UX380_CR0,4,380,562_.jpg",
    },
    {
        nota: 8,
        nome: "Solo Leveling",
        lancamento: "2018",
        genero: ["Shounen"],
        tempo: "Incompleto",
        tipo: "Manwha",
        cover: "https://cdn.myanimelist.net/images/manga/3/222295.jpg",
    },
    {
        nota: 8,
        nome: "Dandadan",
        lancamento: "2021",
        genero: ["Shounen", "Sobrenatural"],
        tempo: "Incompleto",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/2/248746.jpg",
    },
    {
        nota: 8,
        nome: "Jujutsu Kaisen",
        lancamento: "2020",
        genero: ["Sobrenatural"],
        tempo: "Completo",
        tipo: "Anime",
        cover: "https://cdn.myanimelist.net/images/anime/1171/109222.jpg",
    },
    {
        nota: 8,
        nome: "Tokyo Revengers",
        lancamento: "2017",
        genero: ["Drama", "Arte Marcial"],
        tempo: "Incompleto",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/3/196272.jpg",
    },
    {
        nota: 8,
        nome: "Uzumaki",
        lancamento: "1998",
        genero: ["Seinen", "Terror"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/3/185972.jpg",
    },
    {
        nota: 8,
        nome: "Taxi Driver",
        lancamento: "1976",
        genero: ["Thriller", "Terror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/ekstpH614fwDX8DUln1a2Opz0N8.jpg",
    },
    {
        nota: 8,
        nome: "Creep",
        lancamento: "2014",
        genero: ["Thriller", "Terror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/qn53D574tT0YRyLgirEFHQwGUXw.jpg",
    },
    {
        nota: 8,
        nome: "Creep 2",
        lancamento: "2017",
        genero: ["Thriller", "Terror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/a0m7WciFnBqpcyH1Yi8i4tdvk0k.jpg",
    },
    {
        nota: 8,
        nome: "Split",
        lancamento: "2016",
        genero: ["Thriller", "Terror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://m.media-amazon.com/images/M/MV5BNTZjNmVjMzAtZjg2Mi00MWNmLTk5NTItOTExZDYwNTE2YmExXkEyXkFqcGc@._V1_QL75_UX190_CR0,0,190,281_.jpg",
    },
    {
        nota: 8,
        nome: "Baki",
        lancamento: "2016",
        genero: ["Luta", "Arte Marcial"],
        tempo: "Completo",
        tipo: "Anime",
        cover: "https://m.media-amazon.com/images/M/MV5BYmI0MTY0NDgtZDJkYy00Mzk0LWFiZjYtODYwODQyOTAwNzhjXkEyXkFqcGc@._V1_QL75_UY562_CR1,0,380,562_.jpg",
    },
    {
        nota: 8,
        nome: "Hajime no Ippo",
        lancamento: "2000",
        genero: ["Drama", "Arte Marcial"],
        tempo: "Incompleto",
        tipo: "Anime",
        cover: "https://cdn.myanimelist.net/images/anime/4/86334.jpg",
    },
    {
        nota: 8,
        nome: "Wall-E",
        lancamento: "2008",
        genero: ["Aventura"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://m.media-amazon.com/images/M/MV5BMjExMTg5OTU0NF5BMl5BanBnXkFtZTcwMjMxMzMzMw@@._V1_QL75_UX380_CR0,0,380,562_.jpg",
    },
    {
        nota: 8,
        nome: "Darling in the FranXX",
        lancamento: "2018",
        genero: ["Drama", "Mecha", "Romance"],
        tempo: "Completo",
        tipo: "Anime",
        cover: "https://cdn.myanimelist.net/images/anime/1614/90408.jpg",
    },
    {
        nota: 8,
        nome: "Sundome",
        lancamento: "2006",
        genero: ["Drama", "Romance", "Ecchi"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/2/267735.jpg",
    },
    {
        nota: 7,
        nome: "Don't Move",
        lancamento: "2024",
        genero: ["Drama", "Terror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/cRDJxdnRb7ikKd6fVJTrGeaL34v.jpg",
    },
    {
        nota: 7,
        nome: "Resident Evil: Death Island",
        lancamento: "2023",
        genero: ["Zumbi", "Terror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://m.media-amazon.com/images/M/MV5BNzg0OWYwOTMtYjVhNy00NzY0LWJiYTMtMGQ3OTczMmEwZmVhXkEyXkFqcGc@._V1_QL75_UX380_CR0,4,380,562_.jpg",
    },
    {
        nota: 7,
        nome: "Homunculus",
        lancamento: "2021",
        genero: ["Terror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://m.media-amazon.com/images/M/MV5BMDhmZTA1MjQtMDRkMi00YTkzLWEyOTUtNGI2YzE5NWJhYzhlXkEyXkFqcGc@._V1_QL75_UY562_CR9,0,380,562_.jpg",
    },
    {
        nota: 7,
        nome: "Glass",
        lancamento: "2019",
        genero: ["Thriller", "Terror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://m.media-amazon.com/images/M/MV5BMTY1OTA2MjI5OV5BMl5BanBnXkFtZTgwNzkxMjU4NjM@._V1_QL75_UY281_CR4,0,190,281_.jpg",
    },
    {
        nota: 7,
        nome: "Sun-Ken Rock",
        lancamento: "2006",
        genero: ["Drama", "Arte Marcial", "Ecchi"],
        tempo: "Incompleto",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/3/166298.jpg",
    },
    {
        nota: 7,
        nome: "Bird Box: Barcelona",
        lancamento: "2023",
        genero: ["Terror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/iTGBHdL12QEpLyRVlykDuiYxzAG.jpg",
    },
    {
        nota: 7,
        nome: "Dead Tube",
        lancamento: "2014",
        genero: ["Seinen"],
        tempo: "Incompleto",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/3/186914.jpg",
    },
    {
        nota: 7,
        nome: "Smile 2",
        lancamento: "2024",
        genero: ["Terror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/ht8Uv9QPv9y7K0RvUyJIaXOZTfd.jpg",
    },
    {
        nota: 7,
        nome: "Stranger Things",
        lancamento: "2016",
        genero: ["Terror"],
        tempo: "Completo",
        tipo: "Série",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/uOOtwVbSr4QDjAGIifLDwpb2Pdl.jpg",
    },
    {
        nota: 7,
        nome: "Brightburn",
        lancamento: "2019",
        genero: ["Terror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/sJWwkYc9ajwnPRSkqj8Aue5JbKz.jpg",
    },
    {
        nota: 7,
        nome: "Spirited Away",
        lancamento: "2001",
        genero: ["Fantasia", "Aventura"],
        tempo: "Completo",
        tipo: "Anime",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
    },
    {
        nota: 7,
        nome: "Dark",
        lancamento: "2017",
        genero: ["Suspense", "Terror"],
        tempo: "Completo",
        tipo: "Série",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/1DLjjvSWMYo17B7wuz6YikB96hH.jpg",
    },
    {
        nota: 7,
        nome: "O menino e a garça",
        lancamento: "2023",
        genero: ["Fantasia"],
        tempo: "Completo",
        tipo: "Anime",
        cover: "https://cdn.myanimelist.net/images/anime/1857/141785l.jpg",
    },
    {
        nota: 7,
        nome: "Furiosa: Mad Max",
        lancamento: "2024",
        genero: ["Ação", "Aventura"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/iADOJ8Zymht2JPMoy3R7xceZprc.jpg",
    },
    {
        nota: 7,
        nome: "You",
        lancamento: "2018",
        genero: ["Terror"],
        tempo: "Completo",
        tipo: "Série",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/oANi0vEE92nuijiZQgPZ88FSxqQ.jpg",
    },
    {
        nota: 7,
        nome: "Disturbia",
        lancamento: "2007",
        genero: ["Suspense", "Terror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/je3sZZpcfPeiR4eIqBKbxomOw6d.jpg",
    },
    {
        nota: 7,
        nome: "World War Z",
        lancamento: "2013",
        genero: ["Terror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/aCnVdvExw6UWSeQfr0tUH3jr4qG.jpg",
    },
    {
        nota: 6,
        nome: "A Quiet Place: Day One",
        lancamento: "2023",
        genero: ["Terror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/hU42CRk14JuPEdqZG3AWmagiPAP.jpg",
    },
    {
        nota: 5,
        nome: "Silent Hill",
        lancamento: "2006",
        genero: ["Terror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/r0bEDWO2w4a43K2xTNSF284qOsc.jpg",
    },
    {
        nota: 5,
        nome: "Kick-Ass",
        lancamento: "2010",
        genero: ["Drama"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/iHMbrTHJwocsNvo5murCBw0CwTo.jpg",
    },
];
