export const data = [
    {
        nota: 10,
        nome: "20th Century Boys",
        lancamento: "1999",
        genero: ["Seinen"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/5/260006.jpg",
    },
    {
        nota: 10,
        nome: "Memories of Murder",
        lancamento: "2003",
        genero: ["Suspense", "Mistério"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://m.media-amazon.com/images/M/MV5BYmRjOWE5NmMtYTdkYS00ODFlLWJiMTMtYzE2NDZlZjlkZDQ0XkEyXkFqcGc@._V1_QL75_UX285_CR0,0,285,422_.jpg",
    },
    {
        nota: 10,
        nome: "Kaiji",
        lancamento: "2007",
        genero: ["Seinen", "Aposta"],
        tempo: "Completo",
        tipo: "Anime",
        cover: "https://cdn.myanimelist.net/images/anime/12/80032.jpg",
    },
    {
        nota: 10,
        nome: "House M.D.",
        lancamento: "2004",
        genero: ["Drama"],
        tempo: "Completo",
        tipo: "Série",
        cover: "https://images.justwatch.com/poster/305563849/s718/house.jpg",
    },
    {
        nota: 10,
        nome: "Tengen Toppa Gurren Lagann",
        lancamento: "2007",
        genero: ["Mecha"],
        tempo: "Completo",
        tipo: "Anime",
        cover: "https://cdn.myanimelist.net/images/anime/4/5123.jpg",
    },
    {
        nota: 10,
        nome: "Battle Royale",
        lancamento: "2000",
        genero: ["Seinen"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/1/262978.jpg",
    },
    {
        nota: 10,
        nome: "Inuyashiki",
        lancamento: "2014",
        genero: ["Seinen"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/2/156353.webp",
    },
    {
        nota: 10,
        nome: "Koroshiya 1",
        lancamento: "1998",
        genero: ["Seinen", "Terror"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/3/174206.webp",
    },
    {
        nota: 10,
        nome: "Berserk",
        lancamento: "1989",
        genero: ["Seinen", "Fantasia"],
        tempo: "Incompleto",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/1/157897.jpg",
    },
    {
        nota: 10,
        nome: "Kokou no Hito",
        lancamento: "2007",
        genero: ["Seinen"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/1/324690.jpg",
    },
    {
        nota: 10,
        nome: "Chainsaw Man",
        lancamento: "2018",
        genero: ["Seinen"],
        tempo: "Incompleto",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/3/216464.jpg",
    },
    {
        nota: 10,
        nome: "The Fable",
        lancamento: "2014",
        genero: ["Seinen"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/2/152911.jpg",
    },
    {
        nota: 10,
        nome: "Holyland",
        lancamento: "2000",
        genero: ["Seinen"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/3/258962.jpg",
    },
    {
        nota: 10,
        nome: "21st Century Boys",
        lancamento: "2006",
        genero: ["Seinen"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/2/263856.jpg",
    },
    {
        nota: 10,
        nome: "Adolescence",
        lancamento: "2025",
        genero: ["Drama"],
        tempo: "Completo",
        tipo: "Série",
        cover: "https://m.media-amazon.com/images/M/MV5BNGY1YjBiNzMtYWZhNC00OWViLWE0MzItNjc4YzczOGNiM2I0XkEyXkFqcGc@._V1_QL75_UX285_CR0,0,285,422_.jpg",
    },
    {
        nota: 10,
        nome: "Midsommar",
        lancamento: "2019",
        genero: ["Drama", "Terror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://m.media-amazon.com/images/M/MV5BMzQxNzQzOTQwM15BMl5BanBnXkFtZTgwMDQ2NTcwODM@._V1_QL75_UX380_CR0,0,380,562_.jpg",
    },
    {
        nota: 10,
        nome: "Incantation",
        lancamento: "2022",
        genero: ["Drama", "Terror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://m.media-amazon.com/images/M/MV5BY2U2YjU0M2MtZjIxZC00ZDZjLWI2NjItN2MwMmVhM2RkMjNiXkEyXkFqcGc@._V1_QL75_UY281_CR2,0,190,281_.jpg",
    },
    {
        nota: 10,
        nome: "Blue Lock",
        lancamento: "2018",
        genero: ["Shounen", "Esporte"],
        tempo: "Incompleto",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/5/213340.jpg",
    },
    {
        nota: 10,
        nome: "Freesia",
        lancamento: "2001",
        genero: ["Seinen"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/1/321361.jpg",
    },
    {
        nota: 10,
        nome: "Steins;Gate",
        lancamento: "2011",
        genero: ["Ficção Científica"],
        tempo: "Completo",
        tipo: "Anime",
        cover: "https://m.media-amazon.com/images/M/MV5BZjI1YjZiMDUtZTI3MC00YTA5LWIzMmMtZmQ0NTZiYWM4NTYwXkEyXkFqcGc@._V1_QL75_UX380_CR0,4,380,562_.jpg",
    },
    {
        nota: 10,
        nome: "Hunter x Hunter",
        lancamento: "2011",
        genero: ["Shounen"],
        tempo: "Completo",
        tipo: "Anime",
        cover: "https://m.media-amazon.com/images/M/MV5BYzYxOTlkYzctNGY2MC00MjNjLWIxOWMtY2QwYjcxZWIwMmEwXkEyXkFqcGc@._V1_QL75_UY562_CR7,0,380,562_.jpg",
    },
    {
        nota: 10,
        nome: "Ajin",
        lancamento: "2012",
        genero: ["Seinen", "Terror"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/3/307700.jpg",
    },
    {
        nota: 10,
        nome: "Homunculus",
        lancamento: "2003",
        genero: ["Seinen", "Terror"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/1/318.jpg",
    },
    {
        nota: 10,
        nome: "Death Note",
        lancamento: "2006",
        genero: ["Psicológico"],
        tempo: "Completo",
        tipo: "Anime",
        cover: "https://cdn.myanimelist.net/images/anime/1079/138100.jpg",
    },
    {
        nota: 10,
        nome: "Viral Hit",
        lancamento: "2019",
        genero: ["Drama", "Arte Marcial"],
        tempo: "Incompleto",
        tipo: "Manwha",
        cover: "https://cdn.myanimelist.net/images/manga/1/248716.jpg",
    },
    {
        nota: 10,
        nome: "Lookism",
        lancamento: "2014",
        genero: ["Drama", "Arte Marcial"],
        tempo: "Incompleto",
        tipo: "Manwha",
        cover: "https://upload.wikimedia.org/wikipedia/en/1/17/Lookism_Volume_1_Cover.jpg",
    },
    {
        nota: 10,
        nome: "Chi no Wadachi",
        lancamento: "2017",
        genero: ["Seinen", "Terror", "Psicológico"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/1/200350.jpg",
    },
    {
        nota: 10,
        nome: "Donnie Darko",
        lancamento: "2001",
        genero: ["Drama", "Terror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://m.media-amazon.com/images/M/MV5BMWE3NTYzZmEtM2U5MS00MDZhLTk2ZTQtZTgzNjg0ZGQ5ZjM0XkEyXkFqcGc@._V1_QL75_UX190_CR0,2,190,281_.jpg",
    },
    {
        nota: 10,
        nome: "Parasite",
        lancamento: "2019",
        genero: ["Drama"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://m.media-amazon.com/images/M/MV5BYjk1Y2U4MjQtY2ZiNS00OWQyLWI3MmYtZWUwNmRjYWRiNWNhXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg",
    },
    {
        nota: 10,
        nome: "Cyberpunk: Edgerunners",
        lancamento: "2022",
        genero: ["Ação", "Drama", "Cyberpunk"],
        tempo: "Completo",
        tipo: "Anime",
        cover: "https://m.media-amazon.com/images/M/MV5BM2JkMzM2ZmYtNWU4MS00MjZhLWFhZWUtYWFjYTJkN2RhZDliXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg",
    },
    {
        nota: 9,
        nome: "Bastard",
        lancamento: "2014",
        genero: ["Terror", "Drama"],
        tempo: "Completo",
        tipo: "Manwha",
        cover: "https://cdn.myanimelist.net/images/manga/1/205549.jpg",
    },
    {
        nota: 9,
        nome: "Breaking Bad",
        lancamento: "2008",
        genero: ["Drama"],
        tempo: "Completo",
        tipo: "Série",
        cover: "https://m.media-amazon.com/images/M/MV5BMzU5ZGYzNmQtMTdhYy00OGRiLTg0NmQtYjVjNzliZTg1ZGE4XkEyXkFqcGc@._V1_QL75_UX380_CR0,4,380,562_.jpg",
    },
    {
        nota: 9,
        nome: "Mob Psycho 100",
        lancamento: "2016",
        genero: ["Drama"],
        tempo: "Incompleto",
        tipo: "Anime",
        cover: "https://cdn.myanimelist.net/images/anime/5/79183l.jpg",
    },
    {
        nota: 9,
        nome: "O Show de Truman",
        lancamento: "1998",
        genero: ["Drama"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://m.media-amazon.com/images/M/MV5BNzA3ZjZlNzYtMTdjMy00NjMzLTk5ZGYtMTkyYzNiOGM1YmM3XkEyXkFqcGc@._V1_QL75_UX380_CR0,1,380,562_.jpg",
    },
    {
        nota: 9,
        nome: "I am a Hero",
        lancamento: "2009",
        genero: ["Seinen", "Terror"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/1/121183.jpg",
    },
    {
        nota: 9,
        nome: "Gantz",
        lancamento: "2000",
        genero: ["Seinen", "Terror"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/1/278020.jpg",
    },
    {
        nota: 9,
        nome: "Attack on Titan",
        lancamento: "2013",
        genero: ["Shounen"],
        tempo: "Completo",
        tipo: "Anime",
        cover: "https://cdn.myanimelist.net/images/anime/10/47347.jpg",
    },
    {
        nota: 9,
        nome: "Naruto",
        lancamento: "2002",
        genero: ["Shounen"],
        tempo: "Completo",
        tipo: "Anime",
        cover: "https://cdn.myanimelist.net/images/anime/1141/142503.jpg",
    },
    {
        nota: 9,
        nome: "Ghost in the Shell",
        lancamento: "1995",
        genero: ["Ficção Científica", "Cyberpunk"],
        tempo: "Completo",
        tipo: "Anime",
        cover: "https://m.media-amazon.com/images/M/MV5BNzljMjA3MTQtMjM1OS00OGJjLWJiYzctZDRiMTk1NWI5YzQ5XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg",
    },
    {
        nota: 9,
        nome: "Hideout",
        lancamento: "2010",
        genero: ["Seinen", "Terror"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/2/65719.webp",
    },
    {
        nota: 9,
        nome: "Naruto: Shippuden",
        lancamento: "2007",
        genero: ["Shounen"],
        tempo: "Completo",
        tipo: "Anime",
        cover: "https://cdn.myanimelist.net/images/anime/1565/111305.jpg",
    },
    {
        nota: 9,
        nome: "Perfect Blue",
        lancamento: "1997",
        genero: ["Psicológico"],
        tempo: "Completo",
        tipo: "Anime",
        cover: "https://cdn.myanimelist.net/images/anime/1982/114564l.jpg",
    },
    {
        nota: 9,
        nome: "All You Need Is Kill",
        lancamento: "2014",
        genero: ["Seinen", "Ficção Científica"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/1/128447.jpg",
    },
    {
        nota: 9,
        nome: "Charlotte",
        lancamento: "2015",
        genero: ["Drama", "Ficção Científica", "Romance"],
        tempo: "Completo",
        tipo: "Anime",
        cover: "https://cdn.myanimelist.net/images/anime/1826/147276.jpg",
    },
    {
        nota: 9,
        nome: "Kuruko no Basket",
        lancamento: "2012",
        genero: ["Esporte"],
        tempo: "Completo",
        tipo: "Anime",
        cover: "https://cdn.myanimelist.net/images/anime/11/50453.jpg",
    },
    {
        nota: 9,
        nome: "Jojo Bizarre Adventure",
        lancamento: "2012",
        genero: ["Drama", "Ação"],
        tempo: "Completo",
        tipo: "Anime",
        cover: "https://m.media-amazon.com/images/M/MV5BMzIyNzY4NTMtNmVhYS00OWFhLTkwMWMtOGFkNTdmNWU2ZDdiXkEyXkFqcGc@._V1_QL75_UY562_CR7,0,380,562_.jpg",
    },
    {
        nota: 9,
        nome: "One Piece",
        lancamento: "1999",
        genero: ["Drama", "Ação"],
        tempo: "Incompleto",
        tipo: "Anime",
        cover: "https://cdn.myanimelist.net/images/anime/1244/138851.jpg",
    },
    {
        nota: 9,
        nome: "Usogui",
        lancamento: "2006",
        genero: ["Drama", "Ação", "Aposta"],
        tempo: "Incompleto",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/2/283743.jpg",
    },
    {
        nota: 9,
        nome: "Shuumatsu no Valkyrie",
        lancamento: "2017",
        genero: ["Drama", "Ação", "Luta"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/3/209957.jpg",
    },
    {
        nota: 9,
        nome: "Bird Box",
        lancamento: "2018",
        genero: ["Terror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://m.media-amazon.com/images/M/MV5BMjAzMTI1MjMyN15BMl5BanBnXkFtZTgwNzU5MTE2NjM@._V1_QL75_UX380_CR0,0,380,562_.jpg",
    },
    {
        nota: 9,
        nome: "REC",
        lancamento: "2007",
        genero: ["Zumbi", "Terror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://m.media-amazon.com/images/M/MV5BMDEzNDc5ODMtZTAyNi00MTNkLThkNGUtZGE2MDY0MjBiYjMzXkEyXkFqcGc@._V1_QL75_UX380_CR0,4,380,562_.jpg",
    },
    {
        nota: 9,
        nome: "REC 2",
        lancamento: "2009",
        genero: ["Zumbi", "Terror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://m.media-amazon.com/images/M/MV5BMTI4MjQ1MDE1MV5BMl5BanBnXkFtZTcwNzIxMDk0Mw@@._V1_QL75_UY562_CR2,0,380,562_.jpg",
    },
    {
        nota: 9,
        nome: "Shinai naru Boku e Satsui wo Komete",
        lancamento: "2018",
        genero: ["Seinen", "Terror"],
        tempo: "Incompleto",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/1/211898.webp",
    },
    {
        nota: 9,
        nome: "JoJo no Kimyou na Bouken Part 7: Steel Ball Run",
        lancamento: "2004",
        genero: ["Seinen"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/3/179882.jpg",
    },
    {
        nota: 9,
        nome: "JoJo no Kimyou na Bouken Part 6: Stone Ocean",
        lancamento: "1999",
        genero: ["Seinen"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/2/238164.jpg",
    },
    {
        nota: 9,
        nome: "Vagabond",
        lancamento: "1998",
        genero: ["Seinen"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/1/259070.jpg",
    },
    {
        nota: 9,
        nome: "The Horizon",
        lancamento: "2016",
        genero: ["Seinen"],
        tempo: "Completo",
        tipo: "Manwha",
        cover: "https://cdn.myanimelist.net/images/manga/1/229331l.jpg",
    },
    {
        nota: 9,
        nome: "The Boxer",
        lancamento: "2019",
        genero: ["Seinen"],
        tempo: "Completo",
        tipo: "Manwha",
        cover: "https://cdn.myanimelist.net/images/manga/3/251281.jpg",
    },
    {
        nota: 9,
        nome: "Blue Lock",
        lancamento: "2022",
        genero: ["Shounen", "Esporte"],
        tempo: "Completo",
        tipo: "Anime",
        cover: "https://cdn.myanimelist.net/images/anime/1258/126929.jpg",
    },
    {
        nota: 9,
        nome: "Bebê Rena",
        lancamento: "2023",
        genero: ["Drama", "Terror"],
        tempo: "Completo",
        tipo: "Série",
        cover: "https://m.media-amazon.com/images/M/MV5BNzlmY2E1OTUtMjEzZi00Y2YxLWI5NmMtZmZhOWZkMjIzMDJiXkEyXkFqcGc@._V1_QL75_UY562_CR35,0,380,562_.jpg",
    },
    {
        nota: 9,
        nome: "All of Us Are Dead",
        lancamento: "2022",
        genero: ["Zumbi", "Terror"],
        tempo: "Completo",
        tipo: "Série",
        cover: "https://m.media-amazon.com/images/M/MV5BZDY4ZmZhNzMtNjdkMC00NTE3LWFjYzQtOGE4OTllOGY1NTk5XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg",
    },
    {
        nota: 9,
        nome: "O Poço",
        lancamento: "2019",
        genero: ["Drama", "Terror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://m.media-amazon.com/images/M/MV5BYjUyZjNmYmMtNjA1My00ZWMyLTliZGQtODgzZjIxM2Y4NGI1XkEyXkFqcGc@._V1_QL75_UY562_CR7,0,380,562_.jpg",
    },
    {
        nota: 9,
        nome: "O Poço 2",
        lancamento: "2024",
        genero: ["Drama", "Terror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://m.media-amazon.com/images/M/MV5BNzI4YjkyODctMGJmNC00YjBjLTllNjAtNDkxNTJmZjg4MGZkXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg",
    },
    {
        nota: 9,
        nome: "Study Group",
        lancamento: "2019",
        genero: ["Drama", "Arte Marcial"],
        tempo: "Incompleto",
        tipo: "Manwha",
        cover: "https://cdn.myanimelist.net/images/manga/1/260634.jpg",
    },
    {
        nota: 9,
        nome: "Nightcrawler",
        lancamento: "2014",
        genero: ["Drama"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://m.media-amazon.com/images/M/MV5BYjMwMmI5MWQtOTU4OS00OTAyLTg0OTYtNmQ5YzExZTQ3ZWJhXkEyXkFqcGc@._V1_QL75_UY281_CR3,0,190,281_.jpg",
    },
    {
        nota: 9,
        nome: "Druk",
        lancamento: "2020",
        genero: ["Drama"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://m.media-amazon.com/images/M/MV5BNjYxN2EwYjUtNzdiOS00NTgwLTgwNzMtZmE1NGMzYTYxNzBjXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg",
    },
    {
        nota: 9,
        nome: "Alien",
        lancamento: "1979",
        genero: ["Drama", "Terror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://m.media-amazon.com/images/M/MV5BN2NhMDk2MmEtZDQzOC00MmY5LThhYzAtMDdjZGFjOGZjMjdjXkEyXkFqcGc@._V1_QL75_UX380_CR0,6,380,562_.jpg",
    },
    {
        nota: 8,
        nome: "Weak Hero",
        lancamento: "2018",
        genero: ["Drama", "Arte Marcial"],
        tempo: "Completo",
        tipo: "Manwha",
        cover: "https://cdn.myanimelist.net/images/manga/3/232795.jpg",
    },
    {
        nota: 8,
        nome: "Hellsing",
        lancamento: "2021",
        genero: ["Terror"],
        tempo: "Completo",
        tipo: "Anime",
        cover: "https://cdn.myanimelist.net/images/anime/10/19956.jpg",
    },
    {
        nota: 8,
        nome: "Boku Girl",
        lancamento: "2013",
        genero: ["Romance", "Ecchi"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/2/158930l.jpg",
    },
    {
        nota: 8,
        nome: "Teenage Mercenary",
        lancamento: "2018",
        genero: ["Drama", "Arte Marcial"],
        tempo: "Incompleto",
        tipo: "Manwha",
        cover: "https://cdn.myanimelist.net/images/manga/3/260540.jpg",
    },
    {
        nota: 8,
        nome: "God of Blackfield",
        lancamento: "2020",
        genero: ["Drama", "Arte Marcial"],
        tempo: "Incompleto",
        tipo: "Manwha",
        cover: "https://cdn.myanimelist.net/images/manga/2/261694.jpg",
    },
    {
        nota: 8,
        nome: "Happiness",
        lancamento: "2015",
        genero: ["Terror", "Seinen"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/2/161562.jpg",
    },
    {
        nota: 8,
        nome: "Apocalypse no Toride",
        lancamento: "2011 ",
        genero: ["Terror", "Zumbi", "Seinen"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/2/162053.jpg",
    },
    {
        nota: 8,
        nome: "Shigahime",
        lancamento: "2011 ",
        genero: ["Terror", "Seinen"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/2/203507.jpg",
    },
    {
        nota: 8,
        nome: "Manager Kim",
        lancamento: "2021",
        genero: ["Drama", "Arte Marcial"],
        tempo: "Incompleto",
        tipo: "Manwha",
        cover: "https://cdn.myanimelist.net/images/manga/3/260734.jpg",
    },
    {
        nota: 8,
        nome: "Wind Breaker",
        lancamento: "2021",
        genero: ["Drama", "Arte Marcial"],
        tempo: "Incompleto",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/1/244074.jpg",
    },
    {
        nota: 8,
        nome: "A Quiet Place",
        lancamento: "2023",
        genero: ["Terror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://m.media-amazon.com/images/M/MV5BMjI0MDMzNTQ0M15BMl5BanBnXkFtZTgwMTM5NzM3NDM@._V1_QL75_UX285_CR0,0,285,422_.jpg",
    },
    {
        nota: 8,
        nome: "The Walking Dead",
        lancamento: "2010",
        genero: ["Zumbi", "Terror"],
        tempo: "Incompleto",
        tipo: "Série",
        cover: "https://m.media-amazon.com/images/M/MV5BYWQwMGRhNGEtZTNhMy00MzVjLWJhMjItYjcwMDljMTkyNTg2XkEyXkFqcGc@._V1_QL75_UX380_CR0,4,380,562_.jpg",
    },
    {
        nota: 8,
        nome: "I am a Hero",
        lancamento: "2009",
        genero: ["Zombie", "Terror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://m.media-amazon.com/images/M/MV5BMjc4OGZlODYtNGM4Zi00OTFjLTllMDQtODk1ZDMwNWQzNzQ1XkEyXkFqcGc@._V1_QL75_UY562_CR9,0,380,562_.jpg",
    },
    {
        nota: 8,
        nome: "Annihilation",
        lancamento: "2018 ",
        genero: ["Drama", "Terror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://m.media-amazon.com/images/M/MV5BMTk2Mjc2NzYxNl5BMl5BanBnXkFtZTgwMTA2OTA1NDM@._V1_QL75_UX190_CR0,8,190,281_.jpg",
    },
    {
        nota: 8,
        nome: "#Alive",
        lancamento: "2020",
        genero: ["Zumbi", "Terror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://m.media-amazon.com/images/M/MV5BZTI3ZTExYzktMDcwNC00MzUwLTg2NDQtYzBkYjAxMDAyNzVkXkEyXkFqcGc@._V1_QL75_UY562_CR6,0,380,562_.jpg",
    },
    {
        nota: 8,
        nome: "Outside",
        lancamento: "2024",
        genero: ["Zumbi", "Terror"],
        tempo: "Completo",
        tipo: "Série",
        cover: "https://m.media-amazon.com/images/M/MV5BYWNmNDAyOGMtYmVhZC00MGNmLTgyMTgtMWQwODU4YWQyYTRlXkEyXkFqcGc@._V1_QL75_UY562_CR35,0,380,562_.jpg",
    },
    {
        nota: 8,
        nome: "Hajime no Ippo",
        lancamento: "2000",
        genero: ["Drama", "Arte Marcial"],
        tempo: "Incompleto",
        tipo: "Anime",
        cover: "https://cdn.myanimelist.net/images/anime/4/86334.jpg",
    },
    {
        nota: 8,
        nome: "Meus 84m²",
        lancamento: "2025",
        genero: ["Drama", "Suspense"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://m.media-amazon.com/images/M/MV5BM2Y1MjcwMWMtN2IyZi00MGIwLWFiM2YtZjkzZWE1NmJlMGFhXkEyXkFqcGc@._V1_QL75_UY562_CR35,0,380,562_.jpg",
    },
    {
        nota: 8,
        nome: "Classroom of the Elite",
        lancamento: "2017",
        genero: ["Drama", "Arte Marcial"],
        tempo: "Incompleto",
        tipo: "Anime",
        cover: "https://cdn.myanimelist.net/images/anime/7/86829l.jpg",
    },
    {
        nota: 8,
        nome: "Dark",
        lancamento: "2017",
        genero: ["Suspense", "Terror"],
        tempo: "Completo",
        tipo: "Série",
        cover: "https://m.media-amazon.com/images/M/MV5BOWJjMGViY2UtNTAzNS00ZGFjLWFkNTMtMDBiMDMyZTM1NTY3XkEyXkFqcGc@._V1_QL75_UX380_CR0,57,380,562_.jpg",
    },
    {
        nota: 8,
        nome: "Spirited Away",
        lancamento: "2001",
        genero: ["Fantasia", "Aventura"],
        tempo: "Completo",
        tipo: "Anime",
        cover: "https://m.media-amazon.com/images/M/MV5BNTEyNmEwOWUtYzkyOC00ZTQ4LTllZmUtMjk0Y2YwOGUzYjRiXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg",
    },
    {
        nota: 8,
        nome: "X",
        lancamento: "2022",
        genero: ["Thriller", "Terror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://m.media-amazon.com/images/M/MV5BNzQ2MzI5NjQtNmZjZC00ODFhLWE2MjQtNWE0NjljODc0ZGM3XkEyXkFqcGc@._V1_QL75_UY562_CR35,0,380,562_.jpg",
    },
    {
        nota: 8,
        nome: "Pearl",
        lancamento: "2022",
        genero: ["Thriller", "Terror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://m.media-amazon.com/images/M/MV5BNzk0Y2RlZjItZDUzYi00Y2JhLTk5MzMtNjgzYWFmZmUxN2FmXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg",
    },
    {
        nota: 8,
        nome: "Manhole",
        lancamento: "2004",
        genero: ["Terror", "Drama"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/2/67629.jpg",
    },
    {
        nota: 8,
        nome: "Whiplash",
        lancamento: "2014",
        genero: ["Drama"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://m.media-amazon.com/images/M/MV5BMDFjOWFkYzktYzhhMC00NmYyLTkwY2EtYjViMDhmNzg0OGFkXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg",
    },
    {
        nota: 8,
        nome: "Wall-E",
        lancamento: "2008",
        genero: ["Aventura"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://m.media-amazon.com/images/M/MV5BMjExMTg5OTU0NF5BMl5BanBnXkFtZTcwMjMxMzMzMw@@._V1_QL75_UX380_CR0,0,380,562_.jpg",
    },
    {
        nota: 8,
        nome: "Tokyo Gore Police",
        lancamento: "2008",
        genero: ["Thriller", "Terror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://m.media-amazon.com/images/M/MV5BMzhlZDU5NjAtNGQ2Mi00MjNjLTgzMGYtMTBmMzUwYzQzOTRhXkEyXkFqcGc@._V1_QL75_UY562_CR12,0,380,562_.jpg",
    },
    {
        nota: 8,
        nome: "The Professional",
        lancamento: "1994",
        genero: ["Drama"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://m.media-amazon.com/images/M/MV5BNGRkYTNhOWQtYmI0Ni00MjZhLWJmMzAtMTA2Mjg4NGNiNDU0XkEyXkFqcGc@._V1_QL75_UX380_CR0,2,380,562_.jpg",
    },
    {
        nota: 8,
        nome: "The Devil All the Time",
        lancamento: "2020",
        genero: ["Drama", "Terror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://m.media-amazon.com/images/M/MV5BYmExOWUxZDMtZmM1ZS00NjQ4LWEwODAtY2E0N2Y1Y2MzZTkwXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg",
    },
    {
        nota: 8,
        nome: "O Assassino",
        lancamento: "2023",
        genero: ["Drama"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://m.media-amazon.com/images/M/MV5BYzU2MTlkMTctNWI3MC00ODUzLTlmYzQtMzZjYjVmMmYwZGU0XkEyXkFqcGc@._V1_QL75_UX190_CR0,0,190,281_.jpg",
    },
    {
        nota: 8,
        nome: "Furiosa: Mad Max",
        lancamento: "2024",
        genero: ["Ação", "Aventura"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://m.media-amazon.com/images/M/MV5BNTcwYWE1NTYtOWNiYy00NzY3LWIwY2MtNjJmZDkxNDNmOWE1XkEyXkFqcGc@._V1_QL75_UX285_CR0,0,285,422_.jpg",
    },
    {
        nota: 8,
        nome: "Late Night with the Devil",
        lancamento: "2023",
        genero: ["Terror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://m.media-amazon.com/images/M/MV5BYTRiNWZlNGMtOTUwZi00ZjE4LWE1ZjEtNWE4MGQ2ZGU5NDliXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg",
    },
    {
        nota: 8,
        nome: "Baki",
        lancamento: "2016",
        genero: ["Luta", "Arte Marcial"],
        tempo: "Completo",
        tipo: "Anime",
        cover: "https://m.media-amazon.com/images/M/MV5BYmI0MTY0NDgtZDJkYy00Mzk0LWFiZjYtODYwODQyOTAwNzhjXkEyXkFqcGc@._V1_QL75_UY562_CR1,0,380,562_.jpg",
    },
    {
        nota: 8,
        nome: "Alice in Borderland",
        lancamento: "2020",
        genero: ["Drama"],
        tempo: "Completo",
        tipo: "Série",
        cover: "https://m.media-amazon.com/images/M/MV5BZGM4OWUwYjUtODA1My00ZjgxLWE5NjQtYTg4MzA2MjQ1NWU4XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg",
    },
    {
        nota: 8,
        nome: "Cure",
        lancamento: "1999",
        genero: ["Drama", "Terror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://m.media-amazon.com/images/M/MV5BMTI5MmFlZjgtNjNhNC00NTFlLWEzZTctYjNjZDdjYjVmNjExXkEyXkFqcGc@._V1_QL75_UY281_CR7,0,190,281_.jpg",
    },
    {
        nota: 8,
        nome: "20th Century Boys 1: Beginning of the End",
        lancamento: "2008",
        genero: ["Drama", "Terror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://m.media-amazon.com/images/M/MV5BMTMxMzY4NDM2NV5BMl5BanBnXkFtZTcwMjA3MDYyMg@@._V1_QL75_UY422_CR8,0,285,422_.jpg",
    },
    {
        nota: 8,
        nome: "The 8 Show",
        lancamento: "2024",
        genero: ["Drama", "Terror"],
        tempo: "Completo",
        tipo: "Série",
        cover: "https://m.media-amazon.com/images/M/MV5BZjIxNmYxMmUtNGNiMC00ODIyLThhMWEtZWYwNTdiYzFiNDY3XkEyXkFqcGc@._V1_QL75_UX285_CR0,0,285,422_.jpg",
    },
    {
        nota: 8,
        nome: "The Frog",
        lancamento: "2024",
        genero: ["Drama", "Terror"],
        tempo: "Completo",
        tipo: "Série",
        cover: "https://m.media-amazon.com/images/M/MV5BZGM4Y2VhYjMtZGMzYS00YTI5LTk5NWUtMTcxNTJlOGMyZGE2XkEyXkFqcGc@._V1_QL75_UX190_CR0,0,190,281_.jpg",
    },
    {
        nota: 8,
        nome: "Squid Game",
        lancamento: "2021",
        genero: ["Drama", "Terror"],
        tempo: "Completo",
        tipo: "Série",
        cover: "https://m.media-amazon.com/images/M/MV5BYTU3ZDVhNmMtMDVlNC00MDc0LTgwNDMtYWE5MTI2ZGI4YWIwXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg",
    },
    {
        nota: 8,
        nome: "Battle Royale",
        lancamento: "2000",
        genero: ["Seinen"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://m.media-amazon.com/images/M/MV5BNjdlYzJlYzMtMWU3Yi00Y2FjLWJhYmUtNjM3YzdjYzZkOWMwXkEyXkFqcGc@._V1_QL75_UX380_CR0,4,380,562_.jpg",
    },
    {
        nota: 8,
        nome: "Solo Leveling",
        lancamento: "2018",
        genero: ["Shounen"],
        tempo: "Incompleto",
        tipo: "Manwha",
        cover: "https://cdn.myanimelist.net/images/manga/3/222295.jpg",
    },
    {
        nota: 8,
        nome: "Dandadan",
        lancamento: "2021",
        genero: ["Shounen", "Sobrenatural"],
        tempo: "Incompleto",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/2/248746.jpg",
    },
    {
        nota: 8,
        nome: "Jujutsu Kaisen",
        lancamento: "2020",
        genero: ["Sobrenatural"],
        tempo: "Completo",
        tipo: "Anime",
        cover: "https://cdn.myanimelist.net/images/anime/1171/109222.jpg",
    },
    {
        nota: 8,
        nome: "Tokyo Revengers",
        lancamento: "2017",
        genero: ["Drama", "Arte Marcial"],
        tempo: "Incompleto",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/3/196272.jpg",
    },
    {
        nota: 8,
        nome: "O menino e a garça",
        lancamento: "2023",
        genero: ["Fantasia"],
        tempo: "Completo",
        tipo: "Anime",
        cover: "https://cdn.myanimelist.net/images/anime/1857/141785l.jpg",
    },
    {
        nota: 8,
        nome: "Saotome Senshu, Hitakakusu",
        lancamento: "2016",
        genero: ["Esporte", "Romance"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/1/189746.jpg",
    },
    {
        nota: 8,
        nome: "Shotgun Boy",
        lancamento: "2021",
        genero: ["Terror", "Sobrenatural"],
        tempo: "Completo",
        tipo: "Manwha",
        cover: "https://cdn.myanimelist.net/images/manga/2/260422.jpg",
    },
    {
        nota: 8,
        nome: "Uzumaki",
        lancamento: "1998",
        genero: ["Seinen", "Terror"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/3/185972.jpg",
    },
    {
        nota: 8,
        nome: "Darling in the FranXX",
        lancamento: "2018",
        genero: ["Drama", "Mecha", "Romance"],
        tempo: "Completo",
        tipo: "Anime",
        cover: "https://cdn.myanimelist.net/images/anime/1614/90408.jpg",
    },
    {
        nota: 8,
        nome: "Sundome",
        lancamento: "2006",
        genero: ["Drama", "Romance", "Ecchi"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/2/267735.jpg",
    },
    {
        nota: 7,
        nome: "Don't Move",
        lancamento: "2024",
        genero: ["Drama", "Terror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://m.media-amazon.com/images/M/MV5BZmFlMTMyMzQtNmI4NC00YTcyLTgwOGUtMzc4YjcyNDUyOGY3XkEyXkFqcGc@._V1_QL75_UX190_CR0,0,190,281_.jpg",
    },
    {
        nota: 7,
        nome: "Resident Evil: Death Island",
        lancamento: "2023",
        genero: ["Zumbi", "Terror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://m.media-amazon.com/images/M/MV5BNzg0OWYwOTMtYjVhNy00NzY0LWJiYTMtMGQ3OTczMmEwZmVhXkEyXkFqcGc@._V1_QL75_UX380_CR0,4,380,562_.jpg",
    },
    {
        nota: 7,
        nome: "Homunculus",
        lancamento: "2021",
        genero: ["Terror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://m.media-amazon.com/images/M/MV5BMDhmZTA1MjQtMDRkMi00YTkzLWEyOTUtNGI2YzE5NWJhYzhlXkEyXkFqcGc@._V1_QL75_UY562_CR9,0,380,562_.jpg",
    },
    {
        nota: 7,
        nome: "Sun-Ken Rock",
        lancamento: "2006",
        genero: ["Drama", "Arte Marcial", "Ecchi"],
        tempo: "Incompleto",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/3/166298.jpg",
    },
    {
        nota: 7,
        nome: "Bird Box: Barcelona",
        lancamento: "2023",
        genero: ["Terror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://m.media-amazon.com/images/M/MV5BZDkzZWQ1YjctNTUyZi00NmM4LTljNTEtNWFiMzQwM2YzNGZiXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg",
    },
    {
        nota: 7,
        nome: "Dead Tube",
        lancamento: "2014",
        genero: ["Seinen"],
        tempo: "Incompleto",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/3/186914.jpg",
    },
    {
        nota: 7,
        nome: "Sorria 2",
        lancamento: "2024",
        genero: ["Terror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://m.media-amazon.com/images/M/MV5BYTg5OTMyMGMtYzMwNC00NDMyLWE0OGUtMTQ1ODcwM2FjOTM4XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg",
    },
    {
        nota: 7,
        nome: "Stranger Things",
        lancamento: "2016",
        genero: ["Terror"],
        tempo: "Completo",
        tipo: "Série",
        cover: "https://m.media-amazon.com/images/M/MV5BMjg2NmM0MTEtYWY2Yy00NmFlLTllNTMtMjVkZjEwMGVlNzdjXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg",
    },
    {
        nota: 7,
        nome: "You",
        lancamento: "2018",
        genero: ["Terror"],
        tempo: "Completo",
        tipo: "Série",
        cover: "https://m.media-amazon.com/images/M/MV5BMTVlYmRhMWQtNmE0Yi00ODM1LWEzMWEtNTQzZGZhODRmZTE0XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg",
    },
    {
        nota: 7,
        nome: "World War Z",
        lancamento: "2013",
        genero: ["Terror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://m.media-amazon.com/images/M/MV5BODg3ZTM2YWQtZDE5Ny00NGNiLTkzYjgtYWVlYjNkOTg5NDI1XkEyXkFqcGc@._V1_QL75_UX380_CR0,11,380,562_.jpg",
    },
    {
        nota: 6,
        nome: "A Quiet Place: Day One",
        lancamento: "2023",
        genero: ["Terror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://m.media-amazon.com/images/M/MV5BMDdjZTljZWMtMDIwNi00MTA5LTkxZmItNmY0NDA3ZDM0N2M2XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg",
    },
    {
        nota: 5,
        nome: "Silent Hill",
        lancamento: "2006",
        genero: ["Terror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://m.media-amazon.com/images/M/MV5BYTczZmZlZmEtODU4ZS00YzgzLThiMDUtMGE0ZmJhYzdhZGY5XkEyXkFqcGc@._V1_QL75_UY562_CR0,0,380,562_.jpg",
    },
    {
        nota: 5,
        nome: "Kick-Ass",
        lancamento: "2010",
        genero: ["Drama"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://m.media-amazon.com/images/M/MV5BMTMzNzEzMDYxM15BMl5BanBnXkFtZTcwMTc0NTMxMw@@._V1_QL75_UX190_CR0,0,190,281_.jpg",
    },
];
