export const data = [
    {
        nota: 10,
        nome: "20th Century Boys",
        lancamento: "1999",
        genero: ["Apocalipse"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/5/260006.jpg",
    },
    {
        nota: 10,
        nome: "21st Century Boys",
        lancamento: "2006",
        genero: ["Apocalipse"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/2/263856.jpg",
    },
    {
        nota: 10,
        nome: "Memories of Murder",
        lancamento: "2003",
        genero: ["Suspense", "Crime", "Psicológico", "K-Drama"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/jcgUjx1QcupGzjntTVlnQ15lHqy.jpg",
    },
    {
        nota: 10,
        nome: "House M.D.",
        lancamento: "2004",
        genero: ["Narrativa", "Suspense", "Psicológico"],
        tempo: "Completo",
        tipo: "Série",
        cover: "https://images.justwatch.com/poster/305563849/s718/house.jpg",
    },
    {
        nota: 10,
        nome: "Kaiji",
        lancamento: "2007",
        genero: ["Aposta", "Psicológico"],
        tempo: "Completo",
        tipo: "Anime",
        cover: "https://cdn.myanimelist.net/images/anime/12/80032.jpg",
    },
    {
        nota: 10,
        nome: "Viral Hit",
        lancamento: "2019",
        genero: ["Arte Marcial", "Crime", "Ação"],
        tempo: "Completo",
        tipo: "Manwha",
        cover: "https://cdn.myanimelist.net/images/manga/1/248716.jpg",
    },
    {
        nota: 10,
        nome: "Lookism",
        lancamento: "2014",
        genero: ["Arte Marcial", "Crime", "Ação"],
        tempo: "Incompleto",
        tipo: "Manwha",
        cover: "https://upload.wikimedia.org/wikipedia/en/1/17/Lookism_Volume_1_Cover.jpg",
    },
    {
        nota: 10,
        nome: "Holyland",
        lancamento: "2000",
        genero: ["Ação", "Arte Marcial", "Psicológico"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/3/258962.jpg",
    },
    {
        nota: 10,
        nome: "Kokou no Hito",
        lancamento: "2007",
        genero: ["Narrativa", "Psicológico"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/1/324690.jpg",
    },
    {
        nota: 10,
        nome: "Freesia",
        lancamento: "2001",
        genero: ["Horror", "Psicológico", "Ação"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/1/321361.jpg",
    },
    {
        nota: 10,
        nome: "Tengen Toppa Gurren Lagann",
        lancamento: "2007",
        genero: ["Ficção Científica", "Ação"],
        tempo: "Completo",
        tipo: "Anime",
        cover: "https://cdn.myanimelist.net/images/anime/4/5123.jpg",
    },
    {
        nota: 10,
        nome: "Homunculus",
        lancamento: "2003",
        genero: ["Horror", "Psicológico"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/1/318.jpg",
    },
    {
        nota: 10,
        nome: "Death Note",
        lancamento: "2006",
        genero: ["Psicológico", "Suspense", "Ação", "Crime"],
        tempo: "Completo",
        tipo: "Anime",
        cover: "https://cdn.myanimelist.net/images/anime/1079/138100.jpg",
    },
    {
        nota: 10,
        nome: "Chi no Wadachi",
        lancamento: "2017",
        genero: ["Horror", "Psicológico"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/1/200350.jpg",
    },
    {
        nota: 10,
        nome: "Parasite",
        lancamento: "2019",
        genero: ["Narrativa", "Suspense", "Psicológico", "K-Drama"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    },
    {
        nota: 9,
        nome: "Sem Piedade",
        lancamento: "2025",
        genero: ["Crime", "K-Drama", "Narrativa", "Investigação", "Ação"],
        tempo: "Completo",
        tipo: "Série",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/AjL335mFBe7LgCqo3w0RNBSbbZU.jpg",
    },
    {
        nota: 9,
        nome: "Revelações",
        lancamento: "2025",
        genero: ["Investigação", "Narrativa", "Psicológico", "Crime", "Drama"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/1SKvcCOWOD1ECEfY7EgHZW04GSd.jpg",
    },
    {
        nota: 9,
        nome: "A Killer Paradox",
        lancamento: "2024",
        genero: ["Thriller", "Ação", "K-Drama", "Investigação"],
        tempo: "Completo",
        tipo: "Série",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/i2yYZGT2If8XcCZS9ASF1g13MiT.jpg",
    },
    {
        nota: 9,
        nome: "Invasão Zumbi",
        lancamento: "2016",
        genero: ["Apocalipse", "Ação", "K-Drama"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/QqHtwk0oHYed26zra9WGQGyBSm.jpg",
    },
    {
        nota: 9,
        nome: "Cyberpunk: Edgerunners",
        lancamento: "2022",
        genero: ["Ficção Científica", "Ação", "Cyberpunk"],
        tempo: "Completo",
        tipo: "Anime",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/lqcDVZ8pyk08AVftMBildDR3QUK.jpg",
    },
    {
        nota: 9,
        nome: "Fire Punch",
        lancamento: "2016",
        genero: ["Narrativa", "Psicológico"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/2/180430.jpg",
    },
    {
        nota: 9,
        nome: "Chainsaw Man",
        lancamento: "2018",
        genero: ["Ação"],
        tempo: "Incompleto",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/3/216464.jpg",
    },
    {
        nota: 9,
        nome: "Ajin",
        lancamento: "2012",
        genero: ["Horror", "Sobrenatural"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/3/307700.jpg",
    },
    {
        nota: 9,
        nome: "The Fable",
        lancamento: "2014",
        genero: ["Ação"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/2/152911.jpg",
    },
    {
        nota: 9,
        nome: "Steins;Gate",
        lancamento: "2011",
        genero: ["Ficção Científica"],
        tempo: "Completo",
        tipo: "Anime",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/5zxePQEsUKLYDh2kpXGQAeInjUU.jpg",
    },
    {
        nota: 9,
        nome: "Bastard",
        lancamento: "2014",
        genero: ["Horror", "Psicológico"],
        tempo: "Completo",
        tipo: "Manwha",
        cover: "https://cdn.myanimelist.net/images/manga/1/205549.jpg",
    },
    {
        nota: 9,
        nome: "Indomável",
        lancamento: "2025",
        genero: ["Investigação", "Narrativa", "Suspense"],
        tempo: "Completo",
        tipo: "Série",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/qm7I9s2OO63x2eYBh5Mi5UwJHzn.jpg",
    },
    {
        nota: 9,
        nome: "The Silent Sea",
        lancamento: "2021",
        genero: ["Ficção Científica", "Investigação", "Suspense", "K-Drama"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/fFT0IgqtCOks4munDTxQwkvNJkd.jpg",
    },
    {
        nota: 9,
        nome: "Os Suspeitos",
        lancamento: "2013",
        genero: ["Thriller", "Investigação", "Psicológico", "Suspense"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/uhviyknTT5cEQXbn6vWIqfM4vGm.jpg",
    },
    {
        nota: 9,
        nome: "Donnie Darko",
        lancamento: "2001",
        genero: ["Horror", "Psicológico", "Suspense"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/fhQoQfejY1hUcwyuLgpBrYs6uFt.jpg",
    },
    {
        nota: 9,
        nome: "Midsommar",
        lancamento: "2019",
        genero: ["Horror", "Psicológico", "Suspense"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/7LEI8ulZzO5gy9Ww2NVCrKmHeDZ.jpg",
    },
    {
        nota: 9,
        nome: "Cisne Negro",
        lancamento: "2010",
        genero: ["Horror", "Psicológico", "Suspense"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/viWheBd44bouiLCHgNMvahLThqx.jpg",
    },
    {
        nota: 9,
        nome: "Incantation",
        lancamento: "2022",
        genero: ["Horror", "Psicológico", "Suspense"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/cWz28oGV3cSajWdziVQbqrYCmnX.jpg",
    },
    {
        nota: 9,
        nome: "The Horizon",
        lancamento: "2016",
        genero: ["Psicológico", "Horror"],
        tempo: "Completo",
        tipo: "Manwha",
        cover: "https://cdn.myanimelist.net/images/manga/1/229331l.jpg",
    },
    {
        nota: 9,
        nome: "Hunter x Hunter",
        lancamento: "2011",
        genero: ["Ação"],
        tempo: "Completo",
        tipo: "Anime",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/i2EEr2uBvRlAwJ8d8zTG2Y19mIa.jpg",
    },
    {
        nota: 9,
        nome: "O Homem nas Trevas",
        lancamento: "2016",
        genero: ["Horror", "Psicológico", "Crime"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/tBtjyqf8oIdeFkis41bdaJzewBh.jpg",
    },
    {
        nota: 9,
        nome: "O Homem nas Trevas 2",
        lancamento: "2021",
        genero: ["Horror", "Psicológico", "Crime"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/bE46qkPtUnff8READ0AYZP9mVj2.jpg",
    },
    {
        nota: 9,
        nome: "Corra",
        lancamento: "2017",
        genero: ["Horror", "Psicológico"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg",
    },
    {
        nota: 9,
        nome: "Berserk",
        lancamento: "1989",
        genero: ["Ação", "Psicológico"],
        tempo: "Incompleto",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/1/157897.jpg",
    },
    {
        nota: 9,
        nome: "O Poço",
        lancamento: "2019",
        genero: ["Horror", "Psicológico", "Suspense"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/iXvQnzy6JCAx1PiQEKXuTY04ZHl.jpg",
    },
    {
        nota: 9,
        nome: "O Poço 2",
        lancamento: "2024",
        genero: ["Horror", "Psicológico", "Suspense"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/tvIpBg12IIA5Dr9Sjn38ygS1vQp.jpg",
    },
    {
        nota: 9,
        nome: "Weak Hero",
        lancamento: "2018",
        genero: ["Arte Marcial", "Crime", "Ação"],
        tempo: "Completo",
        tipo: "Manwha",
        cover: "https://cdn.myanimelist.net/images/manga/3/232795.jpg",
    },
    {
        nota: 9,
        nome: "Ichi the Killer",
        lancamento: "1998",
        genero: ["Horror"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/3/174206.webp",
    },
    {
        nota: 9,
        nome: "Battle Royale",
        lancamento: "2000",
        genero: ["Ação"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/1/262978.jpg",
    },
    {
        nota: 9,
        nome: "Adolescence",
        lancamento: "2025",
        genero: ["Crime", "Investigação", "Suspense"],
        tempo: "Completo",
        tipo: "Série",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/tDHWWReefmOOjBCJZUck8cNwssk.jpg",
    },
    {
        nota: 9,
        nome: "Jojo Part 7: Steel Ball Run",
        lancamento: "2004",
        genero: ["Ação"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/3/179882.jpg",
    },
    {
        nota: 9,
        nome: "Breaking Bad",
        lancamento: "2008",
        genero: ["Crime", "Ação"],
        tempo: "Completo",
        tipo: "Série",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/ztkUQFLlC19CCMYHW9o1zWhJRNq.jpg",
    },
    {
        nota: 9,
        nome: "Usogui",
        lancamento: "2006",
        genero: ["Aposta"],
        tempo: "Incompleto",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/2/283743.jpg",
    },
    {
        nota: 9,
        nome: "The Boxer",
        lancamento: "2019",
        genero: ["Ação", "Psicológico", "Arte Marcial"],
        tempo: "Completo",
        tipo: "Manwha",
        cover: "https://cdn.myanimelist.net/images/manga/3/251281.jpg",
    },
    {
        nota: 9,
        nome: "Vagabond",
        lancamento: "1998",
        genero: ["Ação", "Psicológico"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/1/259070.jpg",
    },
    {
        nota: 9,
        nome: "I am a Hero",
        lancamento: "2009",
        genero: ["Horror", "Psicológico"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/1/121183.jpg",
    },
    {
        nota: 9,
        nome: "Gantz",
        lancamento: "2000",
        genero: ["Horror"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/1/278020.jpg",
    },
    {
        nota: 9,
        nome: "Blue Lock",
        lancamento: "2018",
        genero: ["Esporte"],
        tempo: "Incompleto",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/5/213340.jpg",
    },
    {
        nota: 9,
        nome: "Garota de Fora",
        lancamento: "2018",
        genero: ["Suspense", "Crime"],
        tempo: "Completo",
        tipo: "Série",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/nhuhxiVTm1EvhLkjAy2ywdDE1PA.jpg",
    },
    {
        nota: 8,
        nome: "Gatilho",
        lancamento: "2025",
        genero: ["Investigação", "Narrativa", "Crime", "K-Drama"],
        tempo: "Completo",
        tipo: "Série",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/eAkzEsRyPXdDefFkIDugX6C0tV2.jpg",
    },
    {
        nota: 8,
        nome: "Kuruko no Basket",
        lancamento: "2012",
        genero: ["Esporte"],
        tempo: "Completo",
        tipo: "Anime",
        cover: "https://cdn.myanimelist.net/images/anime/11/50453.jpg",
    },
    {
        nota: 8,
        nome: "One Piece",
        lancamento: "1999",
        genero: ["Ação"],
        tempo: "Incompleto",
        tipo: "Anime",
        cover: "https://cdn.myanimelist.net/images/anime/1451/114315l.jpg",
    },
    {
        nota: 8,
        nome: "The Killer Inside",
        lancamento: "2018",
        genero: ["Horror", "Psicológico"],
        tempo: "Incompleto",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/1/211898.webp",
    },
    {
        nota: 8,
        nome: "Study Group",
        lancamento: "2019",
        genero: ["Arte Marcial", "Ação"],
        tempo: "Incompleto",
        tipo: "Manwha",
        cover: "https://cdn.myanimelist.net/images/manga/1/260634.jpg",
    },
    {
        nota: 8,
        nome: "Blue Lock",
        lancamento: "2022",
        genero: ["Esporte"],
        tempo: "Completo",
        tipo: "Anime",
        cover: "https://cdn.myanimelist.net/images/anime/1258/126929.jpg",
    },
    {
        nota: 8,
        nome: "Shuumatsu no Valkyrie",
        lancamento: "2017",
        genero: ["Arte Marcial", "Ação"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/3/209957.jpg",
    },
    {
        nota: 8,
        nome: "Oppenheimer",
        lancamento: "2023",
        genero: [],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    },
    {
        nota: 8,
        nome: "Druk",
        lancamento: "2020",
        genero: ["Narrativa"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/aDcIt4NHURLKnAEu7gow51Yd00Q.jpg",
    },
    {
        nota: 8,
        nome: "O Abutre",
        lancamento: "2014",
        genero: ["Crime", "Suspense"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/j9HrX8f7GbZQm1BrBiR40uFQZSb.jpg",
    },
    {
        nota: 8,
        nome: "Inuyashiki",
        lancamento: "2014",
        genero: ["Ação"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/2/156353.webp",
    },
    {
        nota: 8,
        nome: "Mob Psycho 100",
        lancamento: "2016",
        genero: ["Sobrenatural"],
        tempo: "Incompleto",
        tipo: "Anime",
        cover: "https://cdn.myanimelist.net/images/anime/5/79183l.jpg",
    },
    {
        nota: 8,
        nome: "Attack on Titan",
        lancamento: "2013",
        genero: ["Ação", "Apocalipse"],
        tempo: "Completo",
        tipo: "Anime",
        cover: "https://cdn.myanimelist.net/images/anime/10/47347.jpg",
    },
    {
        nota: 8,
        nome: "Naruto",
        lancamento: "2002",
        genero: ["Ação"],
        tempo: "Completo",
        tipo: "Anime",
        cover: "https://cdn.myanimelist.net/images/anime/1141/142503.jpg",
    },
    {
        nota: 8,
        nome: "Naruto: Shippuden",
        lancamento: "2007",
        genero: ["Ação"],
        tempo: "Completo",
        tipo: "Anime",
        cover: "https://cdn.myanimelist.net/images/anime/1565/111305.jpg",
    },
    {
        nota: 8,
        nome: "Hideout",
        lancamento: "2010",
        genero: ["Horror", "Psicológico"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/2/65719.webp",
    },
    {
        nota: 8,
        nome: "Perfect Blue",
        lancamento: "1997",
        genero: ["Psicológico", "Suspense"],
        tempo: "Completo",
        tipo: "Anime",
        cover: "https://cdn.myanimelist.net/images/anime/1982/114564l.jpg",
    },
    {
        nota: 8,
        nome: "Ghost in the Shell",
        lancamento: "1995",
        genero: ["Ficção Científica", "Cyberpunk", "Ação"],
        tempo: "Completo",
        tipo: "Anime",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/9gC88zYUBARRSThcG93MvW14sqx.jpg",
    },
    {
        nota: 8,
        nome: "Charlotte",
        lancamento: "2015",
        genero: ["Ficção Científica", "Romance"],
        tempo: "Completo",
        tipo: "Anime",
        cover: "https://cdn.myanimelist.net/images/anime/1826/147276.jpg",
    },
    {
        nota: 8,
        nome: "Jojo Bizarre Adventure",
        lancamento: "2012",
        genero: ["Ação"],
        tempo: "Completo",
        tipo: "Anime",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/ogAWwbh3frWtiTyyXrZaVFtqCgp.jpg",
    },
    {
        nota: 8,
        nome: "Jojo Part 6: Stone Ocean",
        lancamento: "1999",
        genero: ["Ação"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/2/238164.jpg",
    },
    {
        nota: 8,
        nome: "Teenage Mercenary",
        lancamento: "2018",
        genero: ["Arte Marcial", "Crime", "Ação"],
        tempo: "Incompleto",
        tipo: "Manwha",
        cover: "https://cdn.myanimelist.net/images/manga/3/260540.jpg",
    },
    {
        nota: 8,
        nome: "God of Blackfield",
        lancamento: "2020",
        genero: ["Arte Marcial", "Crime", "Ação"],
        tempo: "Incompleto",
        tipo: "Manwha",
        cover: "https://cdn.myanimelist.net/images/manga/2/261694.jpg",
    },
    {
        nota: 8,
        nome: "All You Need Is Kill",
        lancamento: "2014",
        genero: ["Ficção Científica"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/1/128447.jpg",
    },
    {
        nota: 8,
        nome: "Shigahime",
        lancamento: "2011",
        genero: ["Horror"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/2/203507.jpg",
    },
    {
        nota: 8,
        nome: "It",
        lancamento: "2017",
        genero: ["Horror", "Thriller"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/9E2y5Q7WlCVNEhP5GiVTjhEhx1o.jpg",
    },
    {
        nota: 8,
        nome: "It: Capítulo Dois",
        lancamento: "2019",
        genero: ["Horror", "Thriller"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/zfE0R94v1E8cuKAerbskfD3VfUt.jpg",
    },
    {
        nota: 8,
        nome: "Apocalypse no Toride",
        lancamento: "2011 ",
        genero: ["Horror", "Apocalipse"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/2/162053.jpg",
    },
    {
        nota: 8,
        nome: "Manager Kim",
        lancamento: "2021",
        genero: ["Arte Marcial", "Crime", "Investigação", "Ação"],
        tempo: "Incompleto",
        tipo: "Manwha",
        cover: "https://cdn.myanimelist.net/images/manga/3/260734.jpg",
    },
    {
        nota: 8,
        nome: "Boku Girl",
        lancamento: "2013",
        genero: ["Romance", "Ecchi"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/2/158930l.jpg",
    },
    {
        nota: 8,
        nome: "Happiness",
        lancamento: "2015",
        genero: ["Horror"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/2/161562.jpg",
    },
    {
        nota: 8,
        nome: "Wind Breaker",
        lancamento: "2021",
        genero: ["Arte Marcial", "Ação"],
        tempo: "Incompleto",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/1/244074.jpg",
    },
    {
        nota: 8,
        nome: "Um lugar silencioso",
        lancamento: "2023",
        genero: ["Horror", "Apocalipse"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/nAU74GmpUk7t5iklEp3bufwDq4n.jpg",
    },
    {
        nota: 8,
        nome: "I am a Hero",
        lancamento: "2009",
        genero: ["Apocalipse", "Horror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/4RnmHtCLtbBHD9jagVlcSzJTWX6.jpg",
    },
    {
        nota: 8,
        nome: "Annihilation",
        lancamento: "2018 ",
        genero: ["Horror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/4YRplSk6BhH6PRuE9gfyw9byUJ6.jpg",
    },
    {
        nota: 8,
        nome: "John Wick",
        lancamento: "2014",
        genero: ["Ação", "Thriller", "Crime"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/fZPSd91yGE9fCcCe6OoQr6E3Bev.jpg",
    },
    {
        nota: 8,
        nome: "REC",
        lancamento: "2007",
        genero: ["Apocalipse", "Horror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/5XsVGgo8I12v3KlPcD0r1CNHMC6.jpg",
    },
    {
        nota: 8,
        nome: "REC 2",
        lancamento: "2009",
        genero: ["Apocalipse", "Horror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/fJuIhJ5s8WGNZN3wuk9d84nMjXk.jpg",
    },
    {
        nota: 8,
        nome: "The Walking Dead",
        lancamento: "2010",
        genero: ["Apocalipse", "Horror"],
        tempo: "Incompleto",
        tipo: "Série",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/aN29llVoCFtBTwDZFtqdD9d8dHb.jpg",
    },
    {
        nota: 8,
        nome: "Fear the Walking Dead",
        lancamento: "2015",
        genero: ["Apocalipse", "Horror"],
        tempo: "Incompleto",
        tipo: "Série",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/l7N9aS6VyYvjelKoCB2eZge0Qky.jpg",
    },
    {
        nota: 8,
        nome: "All of Us Are Dead",
        lancamento: "2022",
        genero: ["Apocalipse", "Horror", "K-Drama"],
        tempo: "Completo",
        tipo: "Série",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/pTEFqAjLd5YTsMD6NSUxV6Dq7A6.jpg",
    },
    {
        nota: 8,
        nome: "Bird Box",
        lancamento: "2018",
        genero: ["Horror", "Apocalipse"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/rGfGfgL2pEPCfhIvqHXieXFn7gp.jpg",
    },
    {
        nota: 8,
        nome: "Bebê Rena",
        lancamento: "2023",
        genero: ["Narrativa", "Suspense"],
        tempo: "Completo",
        tipo: "Série",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/tN9OcbkAOPwHSr1sgMornZtQZBx.jpg",
    },
    {
        nota: 8,
        nome: "The Silence",
        lancamento: "2019",
        genero: ["Horror", "Apocalipse"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/k6zhpMq1D18PfO2DEauqF9CTTnb.jpg",
    },
    {
        nota: 8,
        nome: "Alien",
        lancamento: "1979",
        genero: ["Horror", "Suspense", "Ficção Científica"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/vfrQk5IPloGg1v9Rzbh2Eg3VGyM.jpg",
    },
    {
        nota: 8,
        nome: "#Alive",
        lancamento: "2020",
        genero: ["Apocalipse", "Horror", "K-Drama"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/lZPvLUMYEPLTE2df1VW5FHTYC8N.jpg",
    },
    {
        nota: 8,
        nome: "Outside",
        lancamento: "2024",
        genero: ["Apocalipse", "Horror"],
        tempo: "Completo",
        tipo: "Série",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/e2YYJYZrQkodvMGfgdSUH5LBPpr.jpg",
    },
    {
        nota: 8,
        nome: "Manhole",
        lancamento: "2004",
        genero: ["Horror", "Investigação", "Suspense"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/2/67629.jpg",
    },
    {
        nota: 8,
        nome: "Whiplash",
        lancamento: "2014",
        genero: ["Narrativa", "Suspense"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
    },
    {
        nota: 8,
        nome: "Meus 84m²",
        lancamento: "2025",
        genero: ["Investigação", "Suspense", "K-Drama"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/5hlNv3Kd9xovvSgrslWhMriGpZ8.jpg",
    },
    {
        nota: 8,
        nome: "X",
        lancamento: "2022",
        genero: ["Thriller", "Horror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/lopZSVtXzhFY603E9OqF7O1YKsh.jpg",
    },
    {
        nota: 8,
        nome: "Pearl",
        lancamento: "2022",
        genero: ["Thriller", "Horror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/z5uIG81pXyHKg7cUFIu84Wjn4NS.jpg",
    },
    {
        nota: 8,
        nome: "Entrevista com o Demônio",
        lancamento: "2023",
        genero: ["Horror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/mu8LRWT9GHkfiyHm7kgxT6YNvMW.jpg",
    },
    {
        nota: 8,
        nome: "Tokyo Gore Police",
        lancamento: "2008",
        genero: ["Thriller", "Horror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/smQV5DgyUVho8d1R67XnU1BkJAV.jpg",
    },
    {
        nota: 8,
        nome: "O Diabo de Cada Dia",
        lancamento: "2020",
        genero: ["Horror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/sdMZmKVvrnyYbl9Az4L6ehuIrFp.jpg",
    },
    {
        nota: 8,
        nome: "Shotgun Boy",
        lancamento: "2021",
        genero: ["Horror", "Sobrenatural", "Apocalipse"],
        tempo: "Completo",
        tipo: "Manwha",
        cover: "https://cdn.myanimelist.net/images/manga/2/260422.jpg",
    },
    {
        nota: 8,
        nome: "Alice in Borderland",
        lancamento: "2020",
        genero: ["Apocalipse", "K-Drama"],
        tempo: "Completo",
        tipo: "Série",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/Ac8ruycRXzgcsndTZFK6ouGA0FA.jpg",
    },
    {
        nota: 8,
        nome: "Cure",
        lancamento: "1997",
        genero: ["Suspense", "Psicológico", "Crime", "Investigação"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/nLZ2AJFLtMoAAAD54mbT4exj1Wp.jpg",
    },
    {
        nota: 8,
        nome: "20th Century Boys 1: Beginning of the End",
        lancamento: "2008",
        genero: ["Horror", "Apocalipse"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/nb1fd4nZyBLUhkjnAQx5607aBMq.jpg",
    },
    {
        nota: 8,
        nome: "The 8 Show",
        lancamento: "2024",
        genero: ["Horror", "Aposta", "K-Drama"],
        tempo: "Completo",
        tipo: "Série",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/umBNBnKThMmF1QQZixZ7rsYOowq.jpg",
    },
    {
        nota: 8,
        nome: "Quando Ninguem Vê",
        lancamento: "2024",
        genero: ["Horror", "Suspense", "K-Drama"],
        tempo: "Completo",
        tipo: "Série",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/uMl2TzRs1LzTR9jyRNHnf5keqMV.jpg",
    },
    {
        nota: 8,
        nome: "Squid Game",
        lancamento: "2021",
        genero: ["Horror", "Aposta", "K-Drama"],
        tempo: "Completo",
        tipo: "Série",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/1QdXdRYfktUSONkl1oD5gc6Be0s.jpg",
    },
    {
        nota: 8,
        nome: "Battle Royale",
        lancamento: "2000",
        genero: ["Horror", "Psicológico"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/gFX7NuBUeKysOB9nEzRqVpHNT32.jpg",
    },
    {
        nota: 8,
        nome: "Clube da luta",
        lancamento: "1999",
        genero: ["Narrativa", "Psicológico", "Suspense"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/jSziioSwPVrOy9Yow3XhWIBDjq1.jpg",
    },
    {
        nota: 8,
        nome: "Solo Leveling",
        lancamento: "2018",
        genero: ["Ação"],
        tempo: "Incompleto",
        tipo: "Manwha",
        cover: "https://cdn.myanimelist.net/images/manga/3/222295.jpg",
    },
    {
        nota: 8,
        nome: "Dandadan",
        lancamento: "2021",
        genero: ["Sobrenatural"],
        tempo: "Incompleto",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/2/248746.jpg",
    },
    {
        nota: 8,
        nome: "Jujutsu Kaisen",
        lancamento: "2018",
        genero: ["Sobrenatural", "Ação"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/3/210341.jpg",
    },
    {
        nota: 8,
        nome: "Jujutsu Kaisen",
        lancamento: "2020",
        genero: ["Sobrenatural", "Ação"],
        tempo: "Completo",
        tipo: "Anime",
        cover: "https://cdn.myanimelist.net/images/anime/1171/109222.jpg",
    },
    {
        nota: 8,
        nome: "Tokyo Revengers",
        lancamento: "2017",
        genero: ["Arte Marcial", "Crime", "Ação"],
        tempo: "Incompleto",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/3/196272.jpg",
    },
    {
        nota: 8,
        nome: "Saotome Senshu, Hitakakusu",
        lancamento: "2016",
        genero: ["Esporte", "Romance"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/1/189746.jpg",
    },
    {
        nota: 8,
        nome: "Classroom of the Elite",
        lancamento: "2017",
        genero: ["Ação"],
        tempo: "Incompleto",
        tipo: "Anime",
        cover: "https://cdn.myanimelist.net/images/anime/7/86829l.jpg",
    },
    {
        nota: 8,
        nome: "Uzumaki",
        lancamento: "1998",
        genero: ["Horror"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/3/185972.jpg",
    },
    {
        nota: 8,
        nome: "Taxi Driver",
        lancamento: "1976",
        genero: ["Thriller", "Horror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/ekstpH614fwDX8DUln1a2Opz0N8.jpg",
    },
    {
        nota: 8,
        nome: "Creep",
        lancamento: "2014",
        genero: ["Thriller", "Horror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/qn53D574tT0YRyLgirEFHQwGUXw.jpg",
    },
    {
        nota: 8,
        nome: "Creep 2",
        lancamento: "2017",
        genero: ["Thriller", "Horror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/a0m7WciFnBqpcyH1Yi8i4tdvk0k.jpg",
    },
    {
        nota: 8,
        nome: "Fragmentado",
        lancamento: "2016",
        genero: ["Thriller", "Horror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/lli31lYTFpvxVBeFHWoe5PMfW5s.jpg",
    },
    {
        nota: 8,
        nome: "Baki",
        lancamento: "2016",
        genero: ["Arte Marcial", "Ação"],
        tempo: "Completo",
        tipo: "Anime",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/j4bL0G8h8k49MuXKYfZqhXqk2rI.jpg",
    },
    {
        nota: 8,
        nome: "Hajime no Ippo",
        lancamento: "2000",
        genero: ["Arte Marcial", "Ação"],
        tempo: "Incompleto",
        tipo: "Anime",
        cover: "https://cdn.myanimelist.net/images/anime/4/86334.jpg",
    },
    {
        nota: 8,
        nome: "Joias Brutas",
        lancamento: "2019",
        genero: ["Narrativa"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/sg0xxJeb3u1C4kAxhSuTwTNpEDt.jpg",
    },
    {
        nota: 8,
        nome: "Coringa",
        lancamento: "2019",
        genero: ["Narrativa", "Suspense", "Psicológico"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
    },
    {
        nota: 8,
        nome: "Wall·E",
        lancamento: "2008",
        genero: ["Romance", "Ficção Científica"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/hbhFnRzzg6ZDmm8YAmxBnQpQIPh.jpg",
    },
    {
        nota: 8,
        nome: "Darling in the FranXX",
        lancamento: "2018",
        genero: ["Ficção Científica", "Romance"],
        tempo: "Completo",
        tipo: "Anime",
        cover: "https://cdn.myanimelist.net/images/anime/1614/90408.jpg",
    },
    {
        nota: 8,
        nome: "Bunny Girl Senpai",
        lancamento: "2018",
        genero: ["Romance", "Sobrenatural"],
        tempo: "Completo",
        tipo: "Anime",
        cover: "https://cdn.myanimelist.net/images/anime/1301/93586.jpg",
    },
    {
        nota: 8,
        nome: "Sundome",
        lancamento: "2006",
        genero: ["Romance", "Ecchi"],
        tempo: "Completo",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/2/267735.jpg",
    },
    {
        nota: 8,
        nome: "28 Years Later",
        lancamento: "2025",
        genero: ["Apocalipse", "Thriller", "Horror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/mIg1qCkVxnAlM2TK3RUF0tdEXlE.jpg",
    },
    {
        nota: 8,
        nome: "28 Weeks Later",
        lancamento: "2007",
        genero: ["Apocalipse", "Thriller", "Horror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/oix0aNv1lvW3nUGspUyvSIBlpbs.jpg",
    },
    {
        nota: 8,
        nome: "Barbarian",
        lancamento: "2025",
        genero: ["Thriller", "Horror", "Sobrenatural"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/idT5mnqPcJgSkvpDX7pJffBzdVH.jpg",
    },
    {
        nota: 8,
        nome: "Ilha do Medo",
        lancamento: "2010",
        genero: ["Investigação", "Suspense", "Horror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/nrmXQ0zcZUL8jFLrakWc90IR8z9.jpg",
    },
    {
        nota: 8,
        nome: "Nada de Novo no Front",
        lancamento: "2022",
        genero: ["Suspense", "Narrativa"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/2IRjbi9cADuDMKmHdLK7LaqQDKA.jpg",
    },
    {
        nota: 8,
        nome: "Terrifier",
        lancamento: "2018",
        genero: ["Thriller", "Horror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/fjXqhGmaeQpB73WerhrYU6HlyV5.jpg",
    },
    {
        nota: 8,
        nome: "Okja",
        lancamento: "2017",
        genero: ["Narrativa", "Ficção Científica"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/lHBYG2NcBMW7UpFL4rSCpsgvz4m.jpg",
    },
    {
        nota: 8,
        nome: "Maze Runner: Correr ou Morrer",
        lancamento: "2014",
        genero: ["Narrativa", "Ficção Científica"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/efAJzIyjYlgdO7fzfMBJcFZqI5v.jpg",
    },
    {
        nota: 8,
        nome: "Cães de Caça",
        lancamento: "2023",
        genero: ["Narrativa", "Ação", "Crime", "K-Drama"],
        tempo: "Completo",
        tipo: "Série",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/3uflkuhQUh2pnT2V8YgsDkjMfrT.jpg",
    },
    {
        nota: 7,
        nome: "American Psycho",
        lancamento: "2000",
        genero: ["Thriller", "Crime", "Ação"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/9uGHEgsiUXjCNq8wdq4r49YL8A1.jpg",
    },
    {
        nota: 7,
        nome: "I, Robot",
        lancamento: "2004",
        genero: ["Ficção Científica", "Crime", "Ação"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/efwv6F2lGaghjPpBRSINHtoEiZB.jpg",
    },
    {
        nota: 7,
        nome: "Eu sou a Lenda",
        lancamento: "2007",
        genero: ["Apocalipse", "Ação"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/iPDkaSdKk2jRLTM65UOEoKtsIZ8.jpg",
    },
    {
        nota: 7,
        nome: "Nosferatu",
        lancamento: "2024",
        genero: ["Horror", "Thriller"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/5qGIxdEO841C0tdY8vOdLoRVrr0.jpg",
    },
    {
        nota: 7,
        nome: "Drive",
        lancamento: "2011",
        genero: ["Thriller", "Crime", "Ação"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/602vevIURmpDfzbnv5Ubi6wIkQm.jpg",
    },
    {
        nota: 7,
        nome: "Texas Chainsaw Massacre",
        lancamento: "2022",
        genero: ["Thriller", "Horror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/7sKiGNWFM15WNyY7LYd5vmb3brO.jpg",
    },
    {
        nota: 7,
        nome: "As Aventuras de PI",
        lancamento: "2012",
        genero: ["Narrativa"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/iLgRu4hhSr6V1uManX6ukDriiSc.jpg",
    },
    {
        nota: 7,
        nome: "O Profissional",
        lancamento: "1994",
        genero: ["Ação", "Crime"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/bxB2q91nKYp8JNzqE7t7TWBVupB.jpg",
    },
    {
        nota: 7,
        nome: "O Assassino",
        lancamento: "2023",
        genero: ["Ação", "Crime"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/e7Jvsry47JJQruuezjU2X1Z6J77.jpg",
    },
    {
        nota: 7,
        nome: "Leave the World Behind",
        lancamento: "2023",
        genero: ["Apocalipse", "Thriller"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/29rhl1xopxA7JlGVVsf1UHfYPvN.jpg",
    },
    {
        nota: 7,
        nome: "The Truman Show",
        lancamento: "1998",
        genero: ["Narrativa"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/vuza0WqY239yBXOadKlGwJsZJFE.jpg",
    },
    {
        nota: 7,
        nome: "Don't Move",
        lancamento: "2024",
        genero: ["Horror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/cRDJxdnRb7ikKd6fVJTrGeaL34v.jpg",
    },
    {
        nota: 7,
        nome: "Resident Evil: Death Island",
        lancamento: "2023",
        genero: ["Apocalipse", "Horror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/qayga07ICNDswm0cMJ8P3VwklFZ.jpg",
    },
    {
        nota: 7,
        nome: "Homunculus",
        lancamento: "2021",
        genero: ["Horror", "Psicológico"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/fnqmGW6N9fxEyPEylC2qT4bbUmd.jpg",
    },
    {
        nota: 7,
        nome: "Glass",
        lancamento: "2019",
        genero: ["Thriller", "Horror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/svIDTNUoajS8dLEo7EosxvyAsgJ.jpg",
    },
    {
        nota: 7,
        nome: "Sun-Ken Rock",
        lancamento: "2006",
        genero: ["Crime", "Arte Marcial", "Ecchi", "Ação"],
        tempo: "Incompleto",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/3/166298.jpg",
    },
    {
        nota: 7,
        nome: "Bird Box: Barcelona",
        lancamento: "2023",
        genero: ["Horror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/iTGBHdL12QEpLyRVlykDuiYxzAG.jpg",
    },
    {
        nota: 7,
        nome: "Dead Tube",
        lancamento: "2014",
        genero: ["Crime", "Horror", "Psicológico"],
        tempo: "Incompleto",
        tipo: "Mangá",
        cover: "https://cdn.myanimelist.net/images/manga/3/186914.jpg",
    },
    {
        nota: 7,
        nome: "Smile 2",
        lancamento: "2024",
        genero: ["Horror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/ht8Uv9QPv9y7K0RvUyJIaXOZTfd.jpg",
    },
    {
        nota: 7,
        nome: "A Fuga das Galinhas - A Ameaça dos Nuggets",
        lancamento: "2023",
        genero: ["Família"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/8O7qM2ue5VHPsu1FFbZSRMpCqwY.jpg",
    },
    {
        nota: 7,
        nome: "Stranger Things",
        lancamento: "2016",
        genero: ["Horror"],
        tempo: "Completo",
        tipo: "Série",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/uOOtwVbSr4QDjAGIifLDwpb2Pdl.jpg",
    },
    {
        nota: 7,
        nome: "Brightburn",
        lancamento: "2019",
        genero: ["Horror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/sJWwkYc9ajwnPRSkqj8Aue5JbKz.jpg",
    },
    {
        nota: 7,
        nome: "Spirited Away",
        lancamento: "2001",
        genero: ["Narrativa"],
        tempo: "Completo",
        tipo: "Anime",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
    },
    {
        nota: 7,
        nome: "Dark",
        lancamento: "2017",
        genero: ["Suspense", "Horror"],
        tempo: "Completo",
        tipo: "Série",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/1DLjjvSWMYo17B7wuz6YikB96hH.jpg",
    },
    {
        nota: 7,
        nome: "O menino e a garça",
        lancamento: "2023",
        genero: ["Narrativa"],
        tempo: "Completo",
        tipo: "Anime",
        cover: "https://cdn.myanimelist.net/images/anime/1857/141785l.jpg",
    },
    {
        nota: 7,
        nome: "Furiosa: Mad Max",
        lancamento: "2024",
        genero: ["Ação"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/iADOJ8Zymht2JPMoy3R7xceZprc.jpg",
    },
    {
        nota: 7,
        nome: "You",
        lancamento: "2018",
        genero: ["Horror", "Thriller"],
        tempo: "Completo",
        tipo: "Série",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/oANi0vEE92nuijiZQgPZ88FSxqQ.jpg",
    },
    {
        nota: 7,
        nome: "A Babá",
        lancamento: "2017",
        genero: ["Thriller"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/wfs8vJ5TfEvKEK8OsUJzx3GriGg.jpg",
    },
    {
        nota: 7,
        nome: "A Babá: Rainha da Morte",
        lancamento: "2020",
        genero: ["Thriller"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/1JnolYGDrhgo5y3rOb0S1VErF4f.jpg",
    },
    {
        nota: 7,
        nome: "Dahmer",
        lancamento: "2018",
        genero: ["Horror", "Suspense"],
        tempo: "Completo",
        tipo: "Série",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/f2PVrphK0u81ES256lw3oAZuF3x.jpg",
    },
    {
        nota: 7,
        nome: "Disturbia",
        lancamento: "2007",
        genero: ["Investigação", "Suspense", "Horror", "Thriller"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/je3sZZpcfPeiR4eIqBKbxomOw6d.jpg",
    },
    {
        nota: 7,
        nome: "World War Z",
        lancamento: "2013",
        genero: ["Horror", "Apocalipse"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/aCnVdvExw6UWSeQfr0tUH3jr4qG.jpg",
    },
    {
        nota: 7,
        nome: "Procurando Nemo",
        lancamento: "2003",
        genero: ["Família"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/eHuGQ10FUzK1mdOY69wF5pGgEf5.jpg",
    },
    {
        nota: 7,
        nome: "Procurando Dory",
        lancamento: "2016",
        genero: ["Família"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/iq0bBYiDe7ttTNBtTwMBqBLPCXJ.jpg",
    },
    {
        nota: 7,
        nome: "Deadpool",
        lancamento: "2016",
        genero: ["Ação", "Crime"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/3E53WEZJqP6aM84D8CckXx4pIHw.jpg",
    },
    {
        nota: 7,
        nome: "Vingadores: Ultimato",
        lancamento: "2019",
        genero: ["Ação", "Família"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/ulzhLuWrPK07P1YkdWQLZnQh1JL.jpg",
    },
    {
        nota: 7,
        nome: "Vingadores: Guerra Infinita",
        lancamento: "2018",
        genero: ["Ação", "Família"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
    },
    {
        nota: 7,
        nome: "Vingadores: Era de Ultron",
        lancamento: "2015",
        genero: ["Ação", "Família"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/4ssDuvEDkSArWEdyBl2X5EHvYKU.jpg",
    },
    {
        nota: 7,
        nome: "Os Vingadores",
        lancamento: "2012",
        genero: ["Ação", "Família"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg",
    },
    {
        nota: 7,
        nome: "Doutor Estranho",
        lancamento: "2016",
        genero: ["Ação", "Família"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/pb4clPWRJ5AKlSFu1HrrHdt5uAw.jpg",
    },
    {
        nota: 7,
        nome: "O Espetacular Homem-Aranha",
        lancamento: "2012",
        genero: ["Ação", "Família"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/jexoNYnPd6vVrmygwF6QZmWPFdu.jpg",
    },
    {
        nota: 7,
        nome: "Homem-Aranha: Sem Volta Para Casa",
        lancamento: "2021",
        genero: ["Ação", "Família"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    },
    {
        nota: 7,
        nome: "Homem-Aranha: Longe de Casa",
        lancamento: "2019",
        genero: ["Ação", "Família"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/4q2NNj4S5dG2RLF9CpXsej7yXl.jpg",
    },
    {
        nota: 7,
        nome: "Homem-Aranha: De Volta ao Lar",
        lancamento: "2017",
        genero: ["Ação", "Família"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/c24sv2weTHPsmDa7jEMN0m2P3RT.jpg",
    },
    {
        nota: 7,
        nome: "Homem-Aranha: Através do Aranhaverso",
        lancamento: "2023",
        genero: ["Ação", "Família"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
    },
    {
        nota: 7,
        nome: "Homem-Aranha: No Aranhaverso",
        lancamento: "2018",
        genero: ["Ação", "Família"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg",
    },
    {
        nota: 7,
        nome: "Godzilla",
        lancamento: "2014",
        genero: ["Ação", "Família"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/zokD6uxR2iWfYM3Y84yGJvnNTK7.jpg",
    },
    {
        nota: 7,
        nome: "Demolidor",
        lancamento: "2003",
        genero: ["Ação", "Família"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/oCDBwSkntYamuw8VJIxMRCtDBmi.jpg",
    },
    {
        nota: 7,
        nome: "Demolidor",
        lancamento: "2015",
        genero: ["Ação", "Família"],
        tempo: "Incompleto",
        tipo: "Série",
        cover: "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/QWbPaDxiB6LW2LjASknzYBvjMj.jpg",
    },
    {
        nota: 7,
        nome: "A Fantástica Fábrica de Chocolate",
        lancamento: "2005",
        genero: ["Família"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/iKP6wg3c6COUe8gYutoGG7qcPnO.jpg",
    },
    {
        nota: 7,
        nome: "As Branquelas",
        lancamento: "2004",
        genero: ["Investigação", "Crime", "Ação"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/aHTUpo45qy9QYIOnVITGGqLoVcA.jpg",
    },
    {
        nota: 7,
        nome: "Detona Ralph",
        lancamento: "2012",
        genero: ["Família"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/zWoIgZ7mgmPkaZjG0102BSKFIqQ.jpg",
    },
    {
        nota: 7,
        nome: "Divertida Mente",
        lancamento: "2015",
        genero: ["Família"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/2H1TmgdfNtsKlU9jKdeNyYL5y8T.jpg",
    },
    {
        nota: 7,
        nome: "Divertida Mente 2",
        lancamento: "2024",
        genero: ["Família"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg",
    },
    {
        nota: 7,
        nome: "Monstros S.A.",
        lancamento: "2001",
        genero: ["Família"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/wFSpyMsp7H0ttERbxY7Trlv8xry.jpg",
    },
    {
        nota: 7,
        nome: "Enrolados",
        lancamento: "2010",
        genero: ["Família"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/ym7Kst6a4uodryxqbGOxmewF235.jpg",
    },
    {
        nota: 7,
        nome: "Zootopia",
        lancamento: "2016",
        genero: ["Família"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/hlK0e0wAQ3VLuJcsfIYPvb4JVud.jpg",
    },
    {
        nota: 7,
        nome: "Hancock",
        lancamento: "2008",
        genero: ["Ação"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/7DyuV2G0hLEqHeueDfOqhZ2DVut.jpg",
    },
    {
        nota: 7,
        nome: "The Karate Kid",
        lancamento: "2010",
        genero: ["Família"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/b1RBy3l297N0c7PHjlz35cClWju.jpg",
    },
    {
        nota: 7,
        nome: "Cobra Kai",
        lancamento: "2018",
        genero: ["Família"],
        tempo: "Incompleto",
        tipo: "Série",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/6POBWybSBDBKjSs1VAQcnQC1qyt.jpg",
    },
    {
        nota: 7,
        nome: "Uma Noite no Museu",
        lancamento: "2006",
        genero: ["Família"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/Pca1hVNgPAUcp6zVHldlboh80R.jpg",
    },
    {
        nota: 7,
        nome: "Bolt: Supercão",
        lancamento: "2008",
        genero: ["Família"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/puAIiFICbqLehrE8X884ZbNxI8N.jpg",
    },
    {
        nota: 7,
        nome: "Guardiões da Galáxia",
        lancamento: "2014",
        genero: ["Família", "Ação", "Ficção Científica"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/r7vmZjiyZw9rpJMQJdXpjgiCOk9.jpg",
    },
    {
        nota: 7,
        nome: "The Flash",
        lancamento: "2014",
        genero: ["Família"],
        tempo: "Incompleto",
        tipo: "Série",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/yZevl2vHQgmosfwUdVNzviIfaWS.jpg",
    },
    {
        nota: 7,
        nome: "Como Treinar o Seu Dragão",
        lancamento: "2010",
        genero: ["Família"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/yfj27wcg80MjSn7Il6iGQ2wkTth.jpg",
    },
    {
        nota: 7,
        nome: "Meu Malvado Favorito",
        lancamento: "2010",
        genero: ["Família"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/sqXerJ5VvfW15xbniuq4CZ77hQJ.jpg",
    },
    {
        nota: 7,
        nome: "Pica-Pau: O Filme",
        lancamento: "2017",
        genero: ["Família"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/vJXWViokoejHZqEn7GWdNMQ4BRv.jpg",
    },
    {
        nota: 7,
        nome: "Os Incríveis",
        lancamento: "2004",
        genero: ["Família"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/9u27l1k3aUj774xOGCCaVX3iFDu.jpg",
    },
    {
        nota: 7,
        nome: "Toy Story",
        lancamento: "1995",
        genero: ["Família"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/q5b86mLRElrbRQf7JBixFZykOA6.jpg",
    },
    {
        nota: 7,
        nome: "A Casa Monstro",
        lancamento: "2006",
        genero: ["Família"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/qBEpDF693Bql7roL6LY3SsNHg52.jpg",
    },
    {
        nota: 7,
        nome: "Monstro vs Aliens",
        lancamento: "2009",
        genero: ["Família"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/rkV9oqoxun8h0aMQAhUR1rY60a1.jpg",
    },
    {
        nota: 7,
        nome: "Alvin e os Esquilos",
        lancamento: "2007",
        genero: ["Família"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/o2WoeYJv9ISS9bw0kKD2cvmg9xN.jpg",
    },
    {
        nota: 7,
        nome: "Era do Gelo",
        lancamento: "2002",
        genero: ["Família"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/A2NR4rJdD6bIVE61T7rhHxrrGvv.jpg",
    },
    {
        nota: 7,
        nome: "Kung Fu Panda",
        lancamento: "2008",
        genero: ["Família"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/f6hXVGOjmwrmMjlPFHgXdFEmA8Y.jpg",
    },
    {
        nota: 7,
        nome: "Madagascar",
        lancamento: "2005",
        genero: ["Família"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/A3xzOyFlWxoGFPG4aUGX8zMS4OA.jpg",
    },
    {
        nota: 7,
        nome: "Megamente",
        lancamento: "2010",
        genero: ["Família"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/kbiEPYIfdRENV7t0KvMZJ2HIfcQ.jpg",
    },
    {
        nota: 7,
        nome: "Rio",
        lancamento: "2011",
        genero: ["Família"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/pPvCSyQCY6Xtl78Qo9o0YStUj6o.jpg",
    },
    {
        nota: 7,
        nome: "Frozen",
        lancamento: "2013",
        genero: ["Família"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/kgwjIb2JDHRhNk13lmSxiClFjVk.jpg",
    },
    {
        nota: 6,
        nome: "Mortal Kombat",
        lancamento: "2021",
        genero: ["Narrativa", "Ação"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/ybrX94xQm8lXYpZAPRmwD9iIbWP.jpg",
    },
    {
        nota: 6,
        nome: "Um lugar silencioso: dia um",
        lancamento: "2023",
        genero: ["Horror", "Apocalipse"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/hU42CRk14JuPEdqZG3AWmagiPAP.jpg",
    },
    {
        nota: 5,
        nome: "A Bela e a Fera",
        lancamento: "2017",
        genero: ["Romance"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/sMw1k27BDUGpLjYiQ6f2Edx3Df5.jpg",
    },
    {
        nota: 5,
        nome: "Silent Hill",
        lancamento: "2006",
        genero: ["Horror"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/r0bEDWO2w4a43K2xTNSF284qOsc.jpg",
    },
    {
        nota: 5,
        nome: "Kick-Ass",
        lancamento: "2010",
        genero: ["Ação", "Arte Marcial"],
        tempo: "Completo",
        tipo: "Filme",
        cover: "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/iHMbrTHJwocsNvo5murCBw0CwTo.jpg",
    },
];
